/* MPC2000 SYS v1.50 and v1.72 for C/C++ 8.00c, cl /AL /G2 /Ox /Gy /Aw:
   the 2K's own records, every DGROUP name the listings have with its type
   and size, and the functions' conventions and parameters. */
#ifndef MPC2K_H
#define MPC2K_H

#include "mpc2krec.h"

#pragma pack(1)
typedef struct SND MPC_STATE;		/* state.inc's name for the same record */

/* sample-memory pool entry, 10 bytes */
struct SMEM_POOL {
	long base;
	long len;
	int next;
};

/* program pad (note) entry, 1Dh bytes, notes 23h..62h */
struct PGM_PAD {
	struct SND __far *snd;
	char field_04;
	unsigned char mode;		/* NORMAL SIMULT VEL SW DCY SW */
	unsigned char sw1;
	unsigned char alt1;
	unsigned char sw2;
	unsigned char alt2;
	unsigned char voice;		/* POLY MONO NOTE OFF */
	unsigned char mute1;
	unsigned char mute2;
	int tune;
	unsigned char attack;
	unsigned char decay;
	unsigned char dcy_mode;
	unsigned char flt_freq;
	unsigned char flt_res;
	unsigned char fenv_attack;
	unsigned char fenv_decay;
	unsigned char fenv_amount;
	unsigned char v_level;
	unsigned char v_attack;
	unsigned char v_start;
	unsigned char v_freq;
	char field_1b;
	char v_pitch;			/* -78h..78h */
};

/* program, 9DEh bytes in a 9E0h arena block */
struct PGM {
	int blk_para;			/* block size, paragraphs */
	char name[16];
	char name_nul;
	unsigned char hdr_note;
	unsigned char hdr_14[8];
	unsigned char midi_pgm;
	unsigned char hdr_1d;
	struct PGM_PAD pad[64];
	struct PGM_MIX mix[64];
	unsigned char padmap[64];	/* pad -> MIDI note */
	struct FXS fxs[2];
	struct FXR fxr[4];
};

/* T_DSP_CHAN's per-channel control block, 14h bytes */
struct DSPC {
	char field_00[10];
	int field_0a;
	int field_0c;
	int field_0e;
	int field_10;
	int field_12;
};

#pragma pack()

/* DGROUP, by v1.72 address; sizes are main's layout, so a buffer can run
   over the names after it */
extern unsigned char FXS_DEFAULT[72];
extern char FXR_DEFAULT[12];
extern int W_005E;
extern unsigned char P_0060[32];
extern char TBL_WINKEYS_00080[70];
extern long STR_00C6;
extern long STR_00CA;
extern long STR_00CE;
extern long STR_00D2;
extern long STR_00D6;
extern long STR_00DA;
extern long STR_00DE;
extern long STR_00E2;
extern long STR_00E6;
extern long STR_00EA;
extern char TBL_00EE[56];
extern char TBL_NAME_CHARSET[19];
extern char TBL_WINKEYS_00139[111];
extern char STR_01A8[14];
extern char STR_01B6[18];
extern char STR_01C8[16];
extern char STR_01D8[18];
extern char STR_01EA[16];
extern char STR_01FA[16];
extern char STR_020A[24];
extern char STR_0222[18];
extern char STR_0234[18];
extern char STR_0246[30];
extern char STR_0264[30];
extern char STR_0282[26];
extern char STR_029C[16];
extern char STR_02AC[20];
extern char STR_02C0[18];
extern char STR_02D2[24];
extern char STR_02EA[24];
extern char STR_0302[18];
#if FW_VERSION == 172
extern char STR_0314[44];
#else
extern char STR_0314[20];
#endif
extern char STR_0340[14];
extern char ERR_MSG_TABLE[80];
extern int G_ERRNO;
extern char SYS_BUILD_DATE[22];
extern char SYS_PRODUCT_NAME[17];
extern char P_03C7;
extern char P_03C8[52];
extern char P_03FC[40];
extern char TBL_WINKEYS_003FC[40];
extern char DL_REC_OUT_8PARA[56];
extern char STR_FLASH_TEST_STATUS[12];
extern char DL_FLASH_MEMORY_TEST[47];
extern unsigned char STR_NOW_TESTING[12];
extern unsigned char STR_BLOCK[7];
extern unsigned char STR_FLASH_WRITE_ERROR[18];
extern unsigned char STR_FLASH_VERIFY_ERROR[19];
extern unsigned char STR_FLASH_MEMORY_OK[16];
extern unsigned char STR_FLASH_CARD_NOT_FOUND[25];
extern unsigned char TBL_WINKEYS_004F8[15];
extern unsigned char STR_TESTING_MEMORY[18];
extern unsigned char STR_OKAY[5];
extern unsigned char STR_FAIL[6];
extern char DL_WAVE_MEMORY_TEST[62];
extern char TBL_WINKEYS_00562[16];
extern char TBL_WINKEYS_005C4[30];
extern int G_PORT_C2_SHADOW;
extern char P_05E4[44];
extern char P_0610;
extern char TBL_0611;
extern int TBL_0612;
extern long FP_POLL_HOOK;
extern int FP_POLL_HOOK_SEG;
extern int P_0708[120];
extern unsigned TBL_PITCH_RATIO[241];
extern int TBL_09DA[101];
extern int TBL_0AA4[100];
extern unsigned char P_0B6C[2];
extern char TBL_0B6E[202];
extern char TBL_0C38[1];
extern char TBL_0C39[11];
extern int W_0C44;
extern signed char G_VOICE_ALLOC_NEXT;
extern char STR_0C48[26];
extern long PTR_STR_PRESS_ENTER;
extern int PTR_STR_PRESS_ENTER_SEG;
extern char TBL_WINKEYS_00C66[16];
extern char TBL_WINKEYS_00C76[16];
extern char P_0C86[16];
extern char TBL_WINKEYS_00C86[16];
extern char TBL_WINKEYS_00C96[16];
extern char TBL_WINKEYS_00CA6[20];
extern char TBL_WINKEYS_00CBA[40];
extern char P_0CE2[66];
extern char TBL_WINKEYS_00CE2[66];
extern char P_0D24[64];
extern char TBL_WINKEYS_00D64[15];
extern char STR_DOUBLE_DASH[3];
extern unsigned char STR_ST_SUFFIX[5];
extern unsigned char STR_ST_SUFFIX_BLANK[5];
extern unsigned char STR_OFF_PADDED[21];
extern unsigned char STR_NO_SOUND_PADDED[21];
extern char STR_BLANK_VALUE[6];
extern char TBL_0DB0[128];
extern char STR_CREDITS_BLANK;
extern char STR_0E31[34];
extern char STR_0E53[17];
extern char STR_0E64[27];
extern char STR_0E7F[16];
extern char STR_0E8F[33];
extern char STR_0EB0[16];
extern char STR_0EC0[29];
extern char STR_0EDD[29];
extern char STR_0EFA[18];
extern char STR_0F0C[30];
extern char STR_0F2A[16];
extern char STR_0F3A[29];
extern char STR_0F57[30];
extern char STR_0F75[13];
extern char STR_0F82[27];
extern char STR_0F9D[34];
extern char STR_0FBF[37];
extern char CREDITS_TABLE[140];
extern char TBL_WINKEYS_DEV_CREDITS[16];
#if FW_VERSION == 172
extern unsigned char TBL_WINKEYS_0100E[76];
#else
extern unsigned char TBL_WINKEYS_0100E[66];
#endif
#if FW_VERSION == 172
extern unsigned char P_10CC[231];
#else
extern unsigned char P_10CC[242];
#endif
extern char MIXSRC_CURSOR;
extern unsigned char DL_MIXER_SETUP[162];
extern char __near TBL_WINKEYS_01264[56];
extern char STR_129C[10];
extern char STR_12A6[10];
extern char STR_12B0[9];
extern char STR_12B9[9];
extern char FX_TYPE_LABELS[16];
extern char STR_12D2[3];
extern char STR_12D5[3];
extern char STR_12D8[13];
extern char STR_12E5[13];
extern char STR_12F2[11];
extern char STR_12FD[3];
extern int P_1300;
extern char P_1302;
extern char STR_1303[13];
extern char STR_1310[13];
extern char STR_131D[11];
extern char FX_SECTION_LABELS[40];
extern char STR_1350[3];
extern char STR_1353[3];
extern char P_1356[2];
extern char P_1358[6];
extern int FXEDIT_CURSOR;
extern char TBL_1360[1];
extern char TBL_1361[1];
extern char B_1362;
extern char B_1363;
extern char B_1364;
extern char B_1365;
extern unsigned char P_1372[30];
extern char TBL_WINKEYS_MIXER[30];
extern char P_1390[78];
extern char P_13DE[88];
extern char TBL_WINKEYS_01436[45];
extern char STR_FX_INPUT[7];
extern char STR_FX_REV_1[5];
extern char STR_FX_MIX_1[5];
extern char TBL_1474[6];
extern long TBL_147A[2];
extern char TBL_WINKEYS_01485[5];
extern char __near P_148A[46];
extern void __far *TBL_14B8[3];
extern char STR_FX_DIST_1[5];
extern char STR_FX_FILT_1[5];
extern char STR_FX_MOD_1[5];
extern char STR_FX_ECHO_1[5];
extern char STR_FX_REV_2[5];
extern char STR_FX_MIX_2[5];
extern char STR_FX_DIST_2[5];
extern char STR_FX_FILT_2[5];
extern char STR_FX_REV_3[5];
extern char STR_FX_MOD_2[5];
extern char STR_FX_ECHO_2[5];
extern char STR_FX_MIX_3[5];
extern char STR_FX_DIST_3[5];
extern char STR_FX_FILT_3[5];
extern char STR_FX_MOD_3[5];
extern char STR_FX_ECHO_3[5];
extern char STR_FX_REV_4[5];
extern char STR_FX_MIX_4[5];
extern char TBL_151E[8];
extern char TBL_1526[8];
extern long TBL_152E[7];
extern char P_154A[6];
extern char P_1550[6];
extern int W_1556;
extern int W_1558;
extern char TBL_155A[1];
extern char TBL_155B[39];
extern int W_1582;
extern int W_1584;
extern char STR_DB[3];
extern char G_FLAG_1589;
extern unsigned char P_158A[1];
extern unsigned char STR_SOLO[5];
extern unsigned char P_1590[1];
extern unsigned char STR_BYPASS[7];
extern unsigned char STR_SK_CLOSE_MIXER[6];
extern unsigned char STR_SK_MIXER[6];
extern int G_FX_BLINK_TICK;
extern char P_15A6[36];
extern char TBL_WINKEYS_015A6[36];
extern char TBL_WINKEYS_015CA[40];
extern char DL_FX_DISTORTION[106];
extern char __near TBL_WINKEYS_4BAND_FILTER[40];
extern char DL_4BAND_FILTER[125];
extern char STR_1701[12];
extern char STR_170D[7];
extern char STR_1714[7];
extern char STR_171B[16];
extern char STR_172B[13];
extern char STR_1738[12];
extern char STR_1744[16];
extern char FX_MOD_TYPE_LABELS[28];
extern char DL_FX_MODULATION[28];
extern char TBL_WINKEYS_FX_CHORUS[40];
extern char P_17B4[40];
extern char __near P_17DC[40];
extern char TBL_WINKEYS_FX_ROTARY[40];
extern char P_1804[88];
extern char TBL_WINKEYS_0185C[40];
extern long STR_1884;
extern long STR_1888;
extern long STR_188C;
extern char STR_1890[6];
extern char FX_PAN_LABELS[16];
extern char P_18A6[98];
extern char TBL_WINKEYS_FX_PITCH_SHIFT[40];
extern char P_1930[26];
extern char STR_FX_DELAY_MS[20];
extern char STR_FX_FEEDBACK[10];
extern char TBL_WINKEYS_01968[40];
extern char TBL_WINKEYS_01990[40];
extern char STR_19B8[10];
extern char STR_19C2[9];
extern char STR_19CB[10];
extern char STR_19D5[7];
extern char FX_OUT_MODE_LABELS[16];
extern char DL_FX_DELAY_ECHO[28];
extern char P_1A08[86];
extern char P_1A5E[100];
extern char TBL_WINKEYS_01AC2[40];
extern char STR_1AEA[11];
extern char STR_1AF5[11];
extern char STR_1B00[11];
extern char STR_1B0B[11];
extern char STR_1B16[8];
extern char STR_1B1E[8];
extern char STR_1B26[8];
extern char FX_REVERB_LABELS[28];
extern char DL_FX_REVERB[61];
extern char STR_FX_NEAR[6];
extern char STR_FX_LF_DAMPING[17];
extern char STR_FX_HF_DAMPING[18];
extern char TBL_WINKEYS_FX_MIXER[30];
extern char STR_1BCE[13];
extern char STR_1BDB[13];
extern char STR_1BE8[14];
extern char FX_ROUTE_LABELS[12];
#if FW_VERSION == 172
extern unsigned char P_1C36[120];
#else
extern unsigned char P_1C36[110];
#endif
extern char TBL_WINKEYS_FX_MIXER_LR[20];
extern char DL_EFFECT_MIXER[29];
extern char STR_LEV_PAN_HDR[8];
extern char STR_REVERB_LBL[9];
extern char P_1CF0[40];
extern char TBL_WINKEYS_COPY_FX[40];
extern char DL_COPY_FX_SETTINGS[94];
extern char P_1D76[64];
extern char P_1DB6[6];
extern char STR_DB_2[3];
extern char P_1DBF;
extern char STR_NEW_PROGRAM_NAME[18];
extern char G_ASSIGN_VIEW_FIELD;
extern char P_1DD3[1];
extern char TBL_PGM_MASTER_LABELS[16];
extern unsigned char TBL_PAD_MODE_LABELS[28];
extern int TBL_ASSIGN_VIEW_ARM[13];
extern char TBL_ASSIGN_VIEW_FIELD_FIX[260];
#if FW_VERSION == 172
extern unsigned char DL_PGM_ASSIGN[118];
#else
extern unsigned char DL_PGM_ASSIGN[108];
#endif
extern unsigned char STR_ALSO_PLAY_NOTE[18];
extern unsigned char STR_IF_OVER_USE[18];
#if FW_VERSION == 172
extern char TBL_WINKEYS_PGM_ASSIGN[70];
#else
extern char TBL_WINKEYS_PGM_ASSIGN[66];
#endif
extern char DL_ASSIGNMENT_VIEW[53];
extern int P_2033;
extern char P_2035[3];
extern char TBL_WINKEYS_02038[60];
extern char DL_INIT_PAD_ASSIGN[74];
extern char TBL_WINKEYS_INIT_PAD_ASSIGN[36];
extern char TBL_DECAY_MODE_LABELS[12];
extern char TBL_VOICE_OVERLAP_LABELS[28];
extern char PARAMS_CURSOR;
extern char VELO_MOD_CURSOR;
extern char VELO_FILTER_CURSOR;
extern char VELO_PITCH_CURSOR;
extern char G_MUTE_ASSIGN_FIELD;
extern unsigned char P_2110[1];
extern char B_2111;
extern char B_2112;
extern char B_2116;
extern char B_2117;
extern char B_2118;
extern char B_2119;
extern char B_211B;
extern char B_211C;
extern char B_211D;
extern char B_211E;
extern char B_211F;
extern char B_2120;
extern char B_2121;
extern char B_2122;
extern char P_2124[10];
extern char TBL_PARAMS_NAV_DOWN[10];
extern char TBL_PARAMS_NAV_LEFT[10];
extern char TBL_PARAMS_NAV_RIGHT[10];
#if FW_VERSION == 172
extern char DL_PGM_PARAMS[188];
#else
extern char DL_PGM_PARAMS[180];
#endif
#if FW_VERSION == 172
extern char P_2208[70];
#else
extern char P_2208[66];
#endif
extern char DL_VELOCITY_MODULATION[120];
extern char P_22C6[31];
extern char L_1D22F[35];
extern char DL_VELO_ENV_FILTER[120];
extern char P_2380[59];
extern char TBL_WINKEYS_023BB[7];
extern char P_23C2[12];
extern char P_23CE[4];
extern char DL_VELO_PITCH[108];
extern char P_243E[66];
extern char DL_MUTE_ASSIGN[96];
extern char TBL_WINKEYS_MUTE_ASSIGN[66];
extern char P_2522;
extern char TBL_IGNORE_RECEIVE_LABELS[16];
#if FW_VERSION == 172
extern char P_2534[146];
#else
extern char P_2534[138];
#endif
#if FW_VERSION == 172
extern char TBL_WINKEYS_PGM_MIDI[60];
#else
extern char TBL_WINKEYS_PGM_MIDI[56];
#endif
extern char PROGRAM_CURSOR;
extern char COPY_PGM_CURSOR;
extern char G_COPY_NOTE_CURSOR;
extern char COPY_PGM_TO[1];
extern char G_LATCHED_PLAY_NOTE;
extern unsigned char STR_NO_PROGRAM[17];
extern char TBL_WINKEYS_026FE[16];
extern char DL_PROGRAM[90];
extern char P_2768[56];
extern char TBL_WINKEYS_PROGRAM[56];
extern char DL_DELETE_PROGRAM[110];
extern char TBL_WINKEYS_DELETE_PGM[40];
extern char STR_CANT_DELETE_PLAYING[28];
extern char DL_DELETE_ALL_PROGRAMS[101];
extern char L_028B7;
extern char TBL_WINKEYS_DELETE_ALL_PGMS[10];
extern char L_028C2[26];
extern char DL_CREATE_NEW_PROGRAM[82];
extern unsigned char TBL_WINKEYS_0292E[30];
extern char X_0294C[15];
extern unsigned char STR_CANT_CREATE_PLAYING[29];
extern char DL_COPY_PROGRAM[68];
extern char TBL_WINKEYS_COPY_PGM[35];
extern char STR_CANT_COPY_PLAYING[25];
extern int L_029F8;
extern char DL_COPY_NOTE_PARAMS[98];
extern char TBL_COPY_NOTE_PARAMS_KEYS[30];
extern char X_02A7A[16];
extern long STR_2A8A;
extern char STR_2A8E;
extern char L_02A8F[3];
extern char P_2A92[2];
extern char P_2A94[6];
extern unsigned char P_2A9A[34];
extern char X_02ABC[44];
extern int L_02AE8;
extern char P_2AEA[19];
extern char TBL_WINKEYS_02AFD[5];
extern char P_2B02[26];
extern char P_2B1C[50];
extern char TBL_BAR_GLYPHS[28];
extern char P_2B6A[2];
extern char P_2B6C[30];
extern char P_2B8A[19];
extern char TBL_WINKEYS_02B9D[5];
extern char P_2BA2[20];
extern char X_02BB7[5];
extern char X_02BBB;
extern char P_2BBC[38];
extern char L_02BE2[12];
extern char TBL_NOTE_GLYPHS[28];
extern char L_02C0A[52];
extern char P_2C3E[6];
extern char L_02C44[13];
extern char TBL_WINKEYS_02C51[5];
extern char P_2C56[10];
extern char X_02C60[16];
extern char P_2C70[50];
extern unsigned char TBL_FX_BUS_LABELS[10];
extern char X_02CAC[5];
extern char L_02CB1;
extern unsigned char TBL_WINKEYS_CHANNEL_SETTINGS[50];
extern char DL_CHANNEL_SETTINGS[46];
extern char X_02D12[42];
extern char X_02D3C[33];
extern char X_02D5D[12];
extern char X_02D69;
extern char TBL_CHANSET_FIELD_X[1];
extern char TBL_CHANSET_FIELD_Y[1];
extern unsigned char CHANSET_VOL_X;
extern unsigned char CHANSET_VOL_Y;
extern unsigned char CHANSET_PAN_X;
extern unsigned char CHANSET_PAN_Y;
extern unsigned char CHANSET_IVOL_X;
extern unsigned char CHANSET_IVOL_Y;
extern char CHANSET_IOUT_X;
extern unsigned char CHANSET_IOUT_Y;
extern char CHANSET_FXLVL_X;
extern unsigned char CHANSET_FXLVL_Y;
extern unsigned char CHANSET_FXBUS_X;
extern unsigned char CHANSET_FXBUS_Y;
extern char CHANSET_FOLLOW_X;
extern unsigned char CHANSET_FOLLOW_Y;
extern unsigned char STR_EXT_SND[3];
extern int X_02D7D;
extern unsigned char B_2D7F;
extern char STR_DEFAULT_SOUND_NAME[18];
extern char TBL_OFF_ON_LABELS[8];
extern char TBL_REC_INPUT_LABELS[3];
extern char DA_X_02D9D[13];
extern char TBL_REC_MODE_LABELS[22];
extern char STR_TIME_TOO_SHORT[8];
extern int X_02DC8;
extern char X_02DCA[16];
extern char REC_CURSOR;
extern unsigned char P_2DDC[16];
extern char X_02DEC[3];
extern int X_02DEF;
extern char X_02DF1;
extern int X_02DF2;
extern char X_02DF4[9];
extern char TBL_WINKEYS_02DFD[11];
extern char BUF_REC_METER_BAR[36];
extern int W_2E2C;
extern char TBL_2E30[3];
extern char P_2E33[3];
extern unsigned char REC_INPUT_X;
extern char REC_INPUT_Y;
extern unsigned char REC_MODE_X;
extern char REC_MODE_Y;
extern unsigned char B_2E3A;
extern char B_2E3B;
extern char REC_THRESH_X;
extern char REC_THRESH_Y;
extern unsigned char REC_TIME_X;
extern char REC_TIME_Y;
extern unsigned char B_2E40;
extern char B_2E41;
extern char TBL_WINKEYS_02E42[66];
extern char P_2E84[69];
extern char X_02EC9[57];
extern char L_02F02[18];
extern char TBL_WINKEYS_02F14[26];
extern char DL_WAITING_FOR_INPUT[48];
extern long X_02F5E;
extern char TBL_WINKEYS_02F62[26];
extern char DL_RECORDING[36];
extern unsigned char DL_SOUND_MEMORY[52];
extern char X_02FD4[58];
extern unsigned char P_300E[3];
extern char B_3011;
extern char B_3015;
extern char B_3019;
extern char B_301D;
extern char B_3021;
extern char B_3025;
extern char B_3029;
extern char B_302D;
extern char TBL_WINKEYS_03030[30];
extern char P_304E[16];
extern char __far *PTR_DL_PROCESSING;
extern int PTR_DL_PROCESSING_SEG;
extern int G_WAVE_ZOOM;
extern long W_3064;
extern int W_3066;
extern char G_SND_EDIT_PAGE;
extern char G_PLAY_MODE;
extern long FP_SND_SECONDARY;
extern int FP_SND_SECONDARY_SEG;
extern char TBL_LOOP_LEN_MODE_LABELS[10];
extern char TBL_EDIT_RANGE_LABELS[54];
extern unsigned char TBL_LEFT_RIGHT_LABELS[12];
extern char TBL_MONO_STEREO_LABELS[14];
extern char P_30CC[4];
extern char X_030D0[44];
extern char P_30FC[31];
extern unsigned char STR_KBYTES[7];
extern unsigned char P_3122[2];
extern unsigned char STR_MBYTES[7];
extern char X_0312B;
extern char DL_SOUND_INFO[106];
extern char STR_EDIT_COPY_TO_RAM[6];
extern char X_0319C[7];
extern char L_031A3[15];
extern char STR_SOUND_NAME_LBL[12];
extern char TBL_WINKEYS_031BE[45];
extern char P_31EB[1];
extern int X_031EC;
extern char DL_DELETE_SOUND[96];
extern char STR_ROM_1[5];
extern char STR_SND_1[5];
extern char TBL_WINKEYS_DELETE_SOUND[20];
extern char L_0326C[15];
extern char P_327B[3];
extern char DL_DELETE_ALL_SOUNDS[98];
extern char TBL_WINKEYS_DELETE_ALL_SOUNDS[25];
extern char X_032FA[5];
extern char P_32FE[1];
extern char L_032FF;
extern char DL_COPY_SOUND[44];
extern char X_0332C[26];
extern char DL_COPY_TO_RAM[72];
extern char TBL_WINKEYS_0338E[36];
extern char TRIM_CURSOR;
extern char START_FINE_CURSOR;
extern char END_FINE_CURSOR;
extern unsigned char STR_ROM_2[5];
extern unsigned char STR_SND_2[6];
extern char DL_TRIM[8];
extern char L_033C8[40];
extern char TBL_WINKEYS_TRIM[35];
extern char L_03413[30];
extern char TBL_WINKEYS_03431[15];
extern char DL_START_FINE[89];
extern char L_1E2F1[13];
extern char P_34A6[3];
extern char L_034A9[8];
extern char L_034B1[7];
extern char X_034B8[3];
extern char L_034BB[20];
extern char L_034CF[5];
extern long L_034D4;
extern char TBL_WINKEYS_034D8[16];
extern char DL_END_FINE[52];
extern char X_0351C[46];
extern char P_354A[21];
extern char L_0355F[20];
extern char L_03573[5];
extern long L_03578;
extern char TBL_WINKEYS_0357C[15];
extern char P_358B[3];
extern char DL_DISCARD[110];
extern char L_035FC[30];
extern char TBL_WINKEYS_DISCARD[40];
extern char LOOP_CURSOR;
extern char LOOP_FINE_CURSOR;
extern unsigned char STR_ROM_3[4];
extern char X_03648;
extern unsigned char STR_SND_3[5];
extern char P_364E[8];
extern char DA_X_03656[31];
extern long X_03675;
extern char L_03679[7];
extern char P_3680[36];
extern char L_036A4[5];
#if FW_VERSION == 172
extern char L_036A9[10];
#else
extern char L_036A9[17];
#endif
extern int L_036BA;
extern char TBL_WINKEYS_036BC[20];
extern unsigned char DL_LOOP_FINE[42];
extern char X_036FA[56];
extern char P_3732[10];
extern char L_0373C[11];
extern char L_03747[20];
extern char L_0375B[5];
extern long L_03760;
extern char TBL_WINKEYS_03764[16];
extern char DL_FIT_TO_LENGTH[119];
extern char L_037EB;
extern char TBL_WINKEYS_FIT_TO_LENGTH[40];
extern unsigned char TBL_ZONE_ACTION_LABELS[6];
extern char X_0381A[52];
extern char X_0384E[55];
extern char L_03885[7];
extern char X_0388C[5];
extern unsigned char STR_ROM_4[5];
extern unsigned char STR_SND_4[2];
extern long X_03898;
extern char P_389C[15];
extern char L_038A6[35];
extern char P_38CE[35];
extern char TBL_WINKEYS_ZONE_START_FINE[45];
extern char DL_ZONE_START_FINE[69];
extern char L_1E7BB[37];
#if FW_VERSION == 172
extern char TBL_WINKEYS_ZONE_END_FINE[11];
#else
extern char TBL_WINKEYS_ZONE_END_FINE[50];
#endif
#if FW_VERSION == 172
extern char tgt_03993[39];
#else
extern char tgt_03993[361];
#endif
extern char TBL_WINKEYS_039BA[16];
extern char DL_ZONE_END_FINE[102];
extern char P_3A30[50];
extern char TBL_WINKEYS_03A62[16];
extern unsigned char DL_ZONE_EDIT[45];
extern unsigned char STR_NEW_NAME[10];
extern unsigned char STR_INSERT_SND[12];
extern unsigned char STR_PRESSING_DO_IT[27];
extern unsigned char STR_SELECTED_EDIT[20];
extern char P_3AE4[2];
extern char TBL_WINKEYS_ZONE_EDIT[46];
extern char G_TRACK_MODE;
extern char DL_SOUND_PARAMS[100];
extern char STR_ZONE_ROM_LBL[5];
extern char STR_ZONE_SND_LBL[5];
extern char P_3B84[30];
extern char TBL_WINKEYS_03BA2[40];
extern char DL_LOADING[26];
extern char STR_EXT_SND_2[5];
extern char STR_EXT_SND_3[5];
extern unsigned char DL_CHANGE_DISK_MSG[2];
extern unsigned char STR_CHANGE_DISK[26];
extern unsigned char P_3C0A[2];
extern char P_3C0C[16];
extern char TBL_WINKEYS_03C0C[16];
extern char DL_CANT_FIND_FILE[66];
extern char P_3C5E[115];
extern char P_3CD1[3];
extern unsigned char STR_NAME_IN_USE[28];
extern char DL_RENAME_FILE[50];
extern char TBL_WINKEYS_FILE_EXISTS[20];
extern char TBL_WINKEYS_RENAME_FILE[20];
extern char DL_FILE_EXISTS[104];
extern char P_3D9E[25];
extern char TBL_WINKEYS_03DB7[31];
extern char DL_LOAD_A_SOUND[74];
extern char P_3E20[40];
extern char P_3E48[2];
extern unsigned char STR_EXT_SND_4[6];
extern char TBL_FILENAME_CHARSET[194];
extern char STR_EXT_SET[5];
extern char STR_EXT_ST1[5];
extern char TBL_MPC60_SOUND_NAMES[340];
extern char TBL_WINKEYS_LOAD_SOUND[36];
extern char DL_LOAD_A_SOUND_CONFIRM[61];
extern char STR_NO_ASSIGN[13];
extern char TBL_WINKEYS_CHANGE_DISK[25];
extern char P_40F7[3];
extern char DL_CHANGE_DISK[78];
extern unsigned char STR_EXT_SND_5[6];
extern char DL_SAVING[22];
extern char STR_CHANGE_DISK_2[26];
extern char P_417E[2];
#if FW_VERSION == 172
extern char TBL_WINKEYS_04180[30];
#else
extern char TBL_WINKEYS_04180[16];
#endif
#if FW_VERSION == 172
extern char P_419E[48];
#else
extern char P_419E[156];
#endif
#if FW_VERSION == 172
extern char TBL_WINKEYS_0423A[70];
#else
extern char TBL_WINKEYS_0423A[66];
#endif
extern unsigned char P_4280[56];
extern unsigned char DL_SOFTKEYS_MIDI_DUMP[46];
extern unsigned char P_42E6[11];
extern unsigned char STR_RECEIVE_READY[9];
extern char P_42FA[11];
extern unsigned char STR_THIS_PAGE_OPEN[19];
extern unsigned char STR_REQUEST_NO[13];
extern unsigned char STR_SND_5[5];
extern char STR_EXCLUSIVE_CH[14];
extern unsigned char STR_NO_SOUND[11];
extern unsigned char STR_SENDING[13];
extern unsigned char STR_RECEIVING[2];
extern char P_4352[14];
extern char P_43C2[15];
extern char TBL_WINKEYS_KEEP_OR_RETRY[31];
extern char DL_KEEP_OR_RETRY[88];
extern char P_4448[46];
extern char TBL_WINKEYS_MONO_TO_STEREO[46];
extern char DL_MONO_TO_STEREO[87];
extern char P_44CD[3];
extern char P_44D0[46];
extern char TBL_WINKEYS_STEREO_TO_MONO[46];
extern char DL_STEREO_TO_MONO[93];
extern char TBL_WINKEYS_0455B[3];
extern char DIVMOD32_STATIC[8];
extern char P_4566[6];
extern char P_456C[8];
extern char P_4574[48];
extern unsigned char P_45A4[44];
extern char L_045D0[26];
extern char L_045EA[62];
extern char P_4628[18];
extern char L_1F41E[27];
extern char L_04655[25];
extern char L_0466E[15];
extern char L_0467D[49];
extern char P_46AE[256];
extern char P_47AE[474];
extern char X_04988[23];
extern char X_0499F[273];
extern char P_4AB0[24];
extern char P_4AC8[24];
extern char P_4AE0[24];
extern char P_4AF8[24];
extern char P_4B10[24];
extern char P_4B28[24];
extern char P_4B40[24];
extern char GLYPH_KNOB_05[24];
extern char GLYPH_KNOB_06[24];
extern char GLYPH_KNOB_07[24];
extern char GLYPH_KNOB_08[24];
extern char GLYPH_KNOB_09[24];
extern char GLYPH_KNOB_10[24];
extern char GLYPH_KNOB_11[24];
extern char GLYPH_KNOB_12[24];
extern char GLYPH_SMALL_1[11];
extern char GLYPH_SMALL_2[11];
extern char P_4C2E[11];
extern char GLYPH_SMALL_4[11];
extern char GLYPH_SMALL_5[11];
extern char GLYPH_SMALL_6[11];
extern char GLYPH_SMALL_7[11];
extern char GLYPH_SMALL_8[11];
extern char GLYPH_SMALL_DASH[22];
extern char GLYPH_PAIR_12[24];
extern char GLYPH_PAIR_34[24];
extern char GLYPH_PAIR_56[24];
extern char GLYPH_PAIR_78[24];
extern char P_4CE6[10];
extern unsigned char P_4CF0[9];
extern char P_4CF9[17];
#if FW_VERSION == 172
extern char P_4D0A[362];
#else
extern char P_4D0A[1];
#endif
extern char P_4E74[3];
extern char X_04E77[55];
extern int TBL_WINKEYS_04EAE;
extern char B_4EB0;
extern char P_4EB2[24];
extern char B_4ECA;
extern char T_DSP_CHAN[40];
extern int SOUND_EVENT_HANDLER;
extern int SOUND_EVENT_HANDLER_SEG;
extern int FP_MAIN_CALLBACK;
extern int FP_MAIN_CALLBACK_SEG;
extern int W_4EFC;
extern int P_4EFE[4][2];
extern int G_DMA_STATUS2_SHADOW;
extern signed char TBL_4F10[128];
extern unsigned TBL_VOICE_AGE_SNAP[32];
extern int CREDITS_SCROLL_TICK;
extern unsigned CREDITS_SCROLL_LINE;
extern unsigned CREDITS_SCROLL_PHASE;
extern long FP_UI_RETURN_SCREEN;
extern int FP_UI_RETURN_SCREEN_SEG;
extern unsigned char FX_DIST_CURSOR;
extern unsigned char FILTER4_CURSOR;
extern unsigned char G_UI_MODE;
extern unsigned char G_UI_FLAG;
extern unsigned char G_UI_SUBMODE;
extern unsigned char FX_MIXER_CURSOR;
extern unsigned char COPY_FX_CURSOR;
extern char B_4FE1;
extern char B_4FE2;
extern char B_4FE4;
extern unsigned char W_4FE6[2];
extern int W_4FE8;
extern int W_4FEA;
extern int W_4FEE;
extern int W_4FF0;
extern int W_5006;
extern unsigned char W_5012[2];
extern int W_5014;
extern int W_5016;
extern int W_501A;
extern int W_501C;
extern int W_5032;
extern unsigned char W_503E[2];
extern int W_5040;
extern int W_5042;
extern int W_5044;
extern int W_5046;
extern int W_5048;
extern unsigned char W_506A[2];
extern int W_506C;
extern int W_506E;
extern int W_5070;
extern int W_5072;
extern int W_5074;
extern char ZONE_START_FINE_CURSOR;
extern int FP_LOADED_SND;
extern int FP_LOADED_SND_SEG;
extern int W_509C;
extern int W_509E;
extern char __far *W_50A0;
extern int W_50A2;
extern long W_50A4;
extern int W_50A6;
extern long W_50A8;
extern int W_50AA;
extern long G_MPC60_LOAD_LEN;
extern int G_MPC60_LOAD_LEN_HI;
extern long PTR_SEQ_LIST_HEAD;
extern int G_OLD_INT4E_OFF;
extern int G_OLD_INT4E_SEG;
extern char BUF_SDS_PACKET;
extern char B_50B9;
extern char B_50BA;
extern char B_50BB;
extern char SDS_PKT_NUM;
extern unsigned char P_50BD[120];
extern char SDS_PKT_CHECKSUM;
extern char B_5136;
extern char W_5138[2];
extern int W_513A;
extern char W_513C[2];
extern int W_513E;
extern char P_5140[48];
extern int P_5170;
extern long FP_SOUND_DLG_CALLBACK;
extern int FP_SOUND_DLG_CALLBACK_SEG;
extern char G_KEEP_RETRY_FOCUS;
extern struct SND __far *PTR_SAMPLE_DATA;
extern struct SMEM_POOL SMEM_POOL[131];
extern char SMEM_POOL_BASE_HI[2];
extern char SMEM_POOL_LEN[2];
extern char SMEM_POOL_LEN_HI[2];
extern char SMEM_POOL_NEXT[1300];
extern int SMEM_POOL_TAIL_NEXT;
extern int SMEM_POOL_USED;
extern int SMEM_POOL_FREE;
extern int W_56A6;
extern int W_56A8;
extern char B_56AA;
extern char P_56AB[19];
extern char B_56BE;
extern char B_56C0;
extern char G_MPC60_PAD_IDX;
extern long FP_56C2;
extern int W_56C4;
extern int W_56C6;
extern int W_56C8;
extern int W_56CA;
extern int W_56CC;
extern int VOICE_HOLD[32];
extern int VOICE_TIMER[32];
extern int TBL_574E[32];
extern int TBL_578E[32];
extern int G_WAVE_VALID;
extern int G_WAVE_COLS_DONE;
extern char G_WAVE_SMEM_START[2];
extern int G_WAVE_SMEM_START_HI;
extern int G_WAVE_SMEM_END;
extern int G_WAVE_SMEM_END_HI;
extern char TBL_WAVE_NEG_PEAK[2];
extern unsigned char TBL_WAVE_POS_PEAK[978];
extern int W_5BAE;
extern int W_5BB0;
extern int G_METER_L_LEVEL;
extern int G_METER_L_PEAK;
extern int G_METER_R_LEVEL;
extern int G_METER_R_PEAK;
extern char G_SMEM_STATE_A[1];
extern char G_SMEM_STATE_B;
extern char W_5BBC[2];
extern int W_5BBE;
extern char TBL_MPC60_SND_HDR[18];
extern int TBL_MPC60_SND_OFS;
extern int TBL_MPC60_SND_OFS_HI;
extern int TBL_MPC60_SND_LEN;
extern int TBL_MPC60_SND_LEN_HI;
extern int TBL_5BDA;
extern char TBL_5BDC[6];
extern int TBL_MPC60_SND_START;
extern int TBL_MPC60_SND_END;
extern int P_5BE6;
extern int P_5BE8;
extern int P_5BEA;
extern char TBL_MPC60_SND_LEVEL;
extern char TBL_5BED[3];
extern int P_5BF0;
extern char P_5BF2[3];
extern char TBL_5BF5;
extern char TBL_5BF6[1952];
extern char P_6396[1];
extern char TBL_MPC60_PAD_SND[34];
extern char P_63B9[160];
extern char TBL_6459[32];
extern char TBL_6479[32];
extern char TBL_6499[32];
extern char G_MPC60_PAD_SEL;
extern int W_64BA;
extern int W_64BC;
extern long W_64BE;
extern int W_64C0;
extern long W_64C2;
extern int W_64C4;
extern long W_64C6;
extern int W_64C8;
extern long W_64CA;
extern int W_64CC;
extern char W_64CE[2];
extern int W_64D0;
extern char W_64D2[2];
extern int W_64D4;
extern long G_EDIT_FIELD_VAL;
extern int G_EDIT_FIELD_VAL_HI;
extern char P_64DA[1948];
extern long G_ZONE_LEN;
extern int G_ZONE_LEN_HI;
extern char P_6C7A[40];
extern char TBL_6CA2[2];
extern char TBL_6CA4[6870];
extern char P_877A[40];
extern int W_87A2;
extern int W_87A4;
extern char P_87B0[54];
extern char B_87E6;
extern long G_ZONE_START;
extern int G_ZONE_START_HI;
extern struct SND __far *PTR_DMA_STATE;
extern char G_PGM_RETURN_PARAMS;
extern char NOTE_HELD[1];
extern char NOTE_HELD_ALT1[1];
extern char NOTE_HELD_ALT2[382];
extern char B_8972;
extern unsigned char BUF_SYSEX_RX[128];
extern unsigned char G_SYSEX_RX_LEN;
extern char G_SYSEX_RX_ACTIVE;
extern char G_FX_EFFECT_SEL;
extern char P_89F8[18];
extern char G_COPY_SRC_PGM;
extern char G_COPY_SRC_NOTE[1];
extern char G_COPY_DST_PGM;
extern char G_COPY_DST_NOTE[1];
extern char B_8A0E[1];
extern unsigned char P_8B9E[256];
extern char G_MIDI_IN_RING_WR;
extern unsigned char G_MIDI_IN_RING_RD;
/* WIN_FIELD_CHANGE_FN and the names after it are one record, the field a
   window edits.  Code that reaches it through WIN, a cast of the first word,
   reloads a member it has just stored; through the scalar names CL carries
   the stored value on. */
struct WIN_FIELD {
	void (__far *change)(void);
	void (__far *draw)(void);
	char flag;
	char digits;
	char seq_mode;
	char b_0b;
	unsigned char x;
	char y;
	unsigned char cur_x;
	char cur_y;
	char box_w;
	char cur_h;
	char box_r;
	char box_b;
	int mode;
	char __far *var;
	long min;
	long max;
	long value;
};
extern long WIN_FIELD_CHANGE_FN;
#define WIN (*(struct WIN_FIELD *)&WIN_FIELD_CHANGE_FN)
extern int WIN_FIELD_CHANGE_FN_SEG;
extern long WIN_FIELD_DRAW_FN;
extern int WIN_FIELD_DRAW_FN_SEG;
extern char G_FLAG_8CA8;
extern char WIN_FIELD_DIGITS;
extern char G_SEQ_MODE;
extern char B_8CAB;
extern unsigned char WIN_FIELD_X;
extern char EDIT_FIELD_Y;
extern unsigned char EDIT_CURSOR_X;
extern char EDIT_CURSOR_Y;
extern char WIN_FIELD_BOX_W;
extern char EDIT_CURSOR_H;
extern char WIN_FIELD_BOX_R;
extern char WIN_FIELD_BOX_B;
extern char WIN_FIELD_MODE;
extern char __far *WIN_FIELD_VAR;
extern long NUM_ENTRY_MIN;
extern int NUM_ENTRY_MIN_HI;
extern long NUM_ENTRY_MAX;
extern int NUM_ENTRY_MAX_HI;
extern long NUM_ENTRY_VALUE;
extern int NUM_ENTRY_VALUE_HI;
extern long NAME_EDIT_CHANGE_FN;
extern char BUF_NAME_EDIT[15];
extern char BUF_NAME_EDIT_LAST;
extern char B_8CDA;
extern char NAME_EDIT_CASE;
extern char NAME_EDIT_LAST_PAD;
extern char G_DSP_CHAN;
extern char B_8CDF;
extern unsigned char G_PAD_NOTE_BASE;
extern char G_VELOCITY_MAX;
extern char G_PAD_INDEX;
extern unsigned char G_PAD_BANK;
extern char G_NOTE_IN[1];
extern char G_VELOCITY_IN;
extern char G_NOTE_CAPTURE;
extern unsigned char SDS_RX_PORT[1];
extern unsigned char SDS_TX_PORT[1];
extern unsigned char SDS_EXCL_CH;
extern char SDS_STEREO_SIDE;
extern char SDS_REQUEST_NUM;
extern char B_8CED[1];
extern char PTR_LCD_STATE[4];
extern char P_8CF2[20];
extern long W_8D06;
extern int W_8D08;
extern long SDS_LOOP_END;
extern int SDS_LOOP_END_HI;
extern long SDS_SAMPLE_LEN;
extern int SDS_SAMPLE_LEN_HI;
extern long SDS_LOOP_LEN;
extern int SDS_LOOP_LEN_HI;
extern char SDS_LOOP_ON;
extern unsigned SDS_SAMPLE_RATE;
extern int SDS_RX_SND_SLOT;
extern int W_8D24;
extern int W_8D26;
extern char SDS_RX_PACKET;
extern int SDS_TX_PACKET;
extern int SDS_SAMPLE_NUM;
extern char SDS_STATE;
extern long SDS_TX_ADDR;
extern int SDS_TX_ADDR_HI;
extern long SDS_RX_ADDR;
extern int SDS_RX_ADDR_HI;
extern unsigned SDS_PACKET_COUNT;
extern unsigned SDS_PKT_WORDS;
extern int SDS_TX_TIME;
extern int SDS_TX_TIMEOUT;
extern char B_8D42;
extern char B_8D43;
extern char P_8D44[2];
extern unsigned char P_8D46;
extern char __far *PTR_MIDI_STATE;
extern long W_8F48;
extern int W_8F4A;
extern int W_8F4C;
extern char P_8F4E[17];
extern char B_8F5F;
extern char B_8F60;
extern char B_8F61;
extern char P_8F62[18];
extern long G_ZONE_END;
extern int ZONE_END_HI;
extern char P_8F78[64];
extern int W_8FB8;
extern char G_PENDING_DMA_MASK;
extern char TBL_SOUND_NAMES[14];
extern char B_8FCA;
extern char B_8FCB;
extern char B_8FCC;
extern char P_8FCD[14];
extern char B_8FDB;
extern char B_8FDC;
extern char B_8FDD;
extern int W_983C;
extern int W_983E;
extern char ASIC_REG181_SHADOW;
extern char P_9842[512];
extern long W_9A42;
extern int W_9A44;
extern long W_9A46;
extern int W_9A48;
extern char P_9A4E[16];
extern char P_9A5E;
extern char VOICE_TABLE[12];
extern char P_9A7A[2];
extern char P_9A7C[2];
extern char P_9A7E[560];
extern struct SND __far *SND_CURRENT;
extern unsigned char PGM_TABLE[96];
extern struct PGM __far *PGM_CURRENT;
extern char __far *PTR_TRACK_DATA;
extern char PAD_INPUT_MODE;
extern char B_9D1C;
extern char W_9D1E[2];
extern long SMEM_SIZE;
extern unsigned SMEM_SIZE_HI;
extern char REC_PEAK_L[2];
extern int REC_PEAK_R;
extern int REC_PEAK_MONO;
extern int REC_TRIG_PEAK;
extern int REC_RING_POS;
extern char G_SAMPLE_MODE;
extern char G_SAMPLE_MODE_PREV;
extern int REC_PREREC_LEN;
extern int REC_LENGTH;
extern int REC_LENGTH_HI;
extern int REC_BUF_ADDR;
extern int REC_BUF_ADDR_HI;
extern int REC_DMA_POS;
extern long W_9D3C;
extern int W_9D3E;
extern char P_9D40;
extern char P_9D42[18];
extern char PTR_SAMPLE_BUF[4];
extern unsigned W_9D58;
extern char B_9D5A[1];
extern int W_9D5B;
extern int W_9D5D;
extern char P_9D5F[16];
extern char B_9D6F;
extern char PGM_SLOT;
extern char MIX_STEREO_SOURCE[1];
extern char MIX_INDIV_SOURCE[2];
extern char RECORD_MIX_CHANGES[3];
extern char B_9D77;
extern char MIDI_VOLUME_VAL;
extern unsigned SAMPLE_TIME;
extern char SAMPLE_INPUT;
extern char G_REC_MODE;
extern char SAMPLE_MONITOR;
extern char SAMPLE_THRESHOLD;
extern unsigned char SAMPLE_PREREC;
extern char PLAY_X_MODE;
extern char ZONE_EDIT_ACTION;
extern char TRIM_LEN_FIX[1];
extern char LOOP_LEN_FIX[1];
extern char ZONE_LEN_FIX;
extern char SND_EDIT_VIEW;
extern char MIDI_VOLUME_RX;
extern char PGM_CHANGE_RX;
extern char MIDI_LOCAL_MODE;
extern unsigned char P_9D89[2];
extern char G_STATE_9D8B;
extern char P_9D8E[18];
extern char P_9DA0[386];
extern int P_9F22;
extern char BUF_XFER[26];
extern int P_9F3E;
extern int P_9F40[242];
extern char P_A124[512];
extern char P_A324[1024];
extern char __far *P_A724;
extern int P_A726;
extern char BSS_TOP[1];
#if FW_VERSION == 172
extern char P_0572[68];
extern char STR_NO_WAVE_RAM[14];
extern char STR_11B3[7];
extern char STR_11BA[6];
extern char STR_1C02[7];
extern char STR_1C09[6];
extern char STR_1C0F[6];
extern char STR_1C15[6];
extern char STR_1C1B[7];
extern char FX_OUT_PAIR_LABELS[20];
extern int FP_2602;
extern int FP_2602_SEG;
extern char P_2606[2];
extern unsigned char P_2608[184];
extern char TBL_WINKEYS_PURGE[40];
extern char L_036B3[7];
extern char P_41CE[108];
extern char P_4360[14];
extern char TBL_WINKEYS_RECEIVE_MODE[30];
extern char P_438C[54];
extern int W_9A4A;
extern char B_9A4C;
extern char B_9D8C;
#endif
#if FW_VERSION != 172
extern char B_980A_V150;
extern char B_980B_V150;
#endif

/* TEXT1 */
int __far mpc_config_rate(void);
int __far L_00026(void);
void __far mpc_rate_caller(void);
long __far _div(int, int);
long __far _ldiv(long, long);
void __far _longjmp(char __far *, int);
long __far ivt_get_vector(int);
void __far ivt_set_vector(int, long);
long __far L_004C8(void);
void __far far_005A2(void);
void __far X_00A5E(void);
void __far X_0188D(void);
void __far far_01AE1(void);
void __near fn_01C45(void);
void __far X_01C64(void);
int __far far_01CA2(void);
void __far L_01CA7(void);
void __near fn_01CB4(void);
void __near fn_01D30(void);
void __far win_key_nop_stub(void);
void __far __pascal disp_list_run(char __far *);
int __far int2F_call_fn5(void);
int __far int2F_call_fn6(char __far *, int);
int __far int2F_call_fn4(char __far *);
int __far int2F_call_fn9(long, int);
int __far int2F_call_fn7(long);
void __far int2F_dispatch_10(void);
int __far int2F_call_fn14(char __far *);
int __far int2F_call_fn20(char __far *);
void __far int2F_dispatch_21(void);
int __far int2F_dispatch_17(void);
void __far __pascal win_keys_merge(char __far *);
void __far int3A_wrapper(int);
char __far pad_bank_get(void);
void __far int3F_wrapper(int);
int __far int38_wrapper(void);
void __far __pascal int38_wrapper_2(int, int, int);
void __far callback_set_main(int, int);
long __far addr_calc_segment(long, int);
long __far timing_calc_rate(int);
long __far __pascal system_init_handler(int, int);
int __near __pascal mem_test_init(int);
void __near __pascal mpc_mode_setup(int, int);
void __far __fastcall __loadds system_setup_2(void);
void __far __fastcall __loadds L_02420(void);
int __near __pascal smem_pool_insert(struct SMEM_POOL);
void __near __pascal smem_pool_remove(int);
int __far __pascal smem_alloc(long);
int __far __pascal midi_status_process(int, int, int, long);
void __far __pascal smem_free(int);
int __far X_025D8(void);
void __far L_02720(void);
void __near __pascal smem_block_init(int, int, int, int, int);
int __near __pascal buffer_init(int __far *, int, int);
int __far X_0286A(void);
int __far dsp_02877(void);
int __near dsp_0292A(void);
long __near smem_read_byte(void);
void __near smem_byte_wrapper(void);
int __near smem_read_word(void);
int __far smem_word_wrapper(void);
int __near v53_read_timer(void);
void __far __pascal smem_poll_ready(unsigned, int);
void __far __pascal pad_note_trigger(unsigned char __far *);
void __near __pascal note_voice_prepare(int, unsigned char __far *, void __far *, long, long, char);
void __near __pascal mpc_ctrl_init(void __far *, void __far *);
void __near __pascal voice_pitch_ratio(void __far *, int, int, int);
void __near __pascal audio_mixing_handler(void __far *, void __far *);
long __near __pascal mpc_status_read(void __far *, void __far *, char);
int __near __pascal mpc_status_wait(void __far *, int, int);
void __near __pascal system_setup(void __far *, long, int, int);
void __near __pascal midi_parse_channel(void __far *, long, long);
void __near __pascal mpc_query_status(char, char, char, void (__far *)(void), void (__far *)(void));
void __far __pascal field_register(long, long, long, char, char, char, long, long);
void __far __pascal far_call_wrapper_1(long, char, char);
void __far __pascal far_035F2(long, char, char, char, long);
void __near mixer_arm_field(void);
void __far __fastcall __loadds L_03698(void);
void __far __fastcall __loadds X_036AE(void);
void __far __fastcall __loadds X_036C4(void);
void __far __fastcall __loadds X_036DC(void);
void __far __fastcall __loadds mixer_setup(void);
void __far X_03716(void);
void __near fn_03724(void);
void __far __fastcall __loadds X_03796(void);
void __far __fastcall __loadds X_037B6(void);
void __far __fastcall __loadds X_037D2(void);
void __far __fastcall __loadds X_037E8(void);
void __far X_037FE(void);
void __near fn_03836(void);
void __near X_03852(void);
void __near X_03890(void);
void __far __fastcall __loadds X_03896(void);
void __far __fastcall __loadds X_038BA(void);
void __far __fastcall __loadds X_038D6(void);
void __far __fastcall __loadds X_038EC(void);
void __near fn_03902(void);
int __near __pascal ui_screen_enter(long, long, long);
void __far __fastcall __loadds X_039A8(void);
void __far __fastcall __loadds L_039C6(void);
void __near fx_dist_arm_field(void);
void __far __fastcall __loadds X_03AEA(void);
void __far __fastcall __loadds X_03B00(void);
void __far __fastcall __loadds X_03B16(void);
void __far __fastcall __loadds X_03B2E(void);
void __far __fastcall __loadds X_03B46(void);
void __far __fastcall __loadds filter4_paint(void);
void __near midi_note_handler(void);
void __far __fastcall __loadds filter4_up(void);
void __far __fastcall __loadds filter4_down(void);
void __far __fastcall __loadds filter4_left(void);
void __far __fastcall __loadds filter4_right(void);
void __far __pascal ctrl_change_table_dispatch(long);
void __far __fastcall __loadds X_03F3E(void);
void __near fx_mod_arm_field(void);
void __far __fastcall __loadds fx_chorus_up(void);
void __far __fastcall __loadds fx_chorus_down(void);
void __far __fastcall __loadds fx_chorus_left(void);
void __far __fastcall __loadds fx_chorus_right(void);
void __far __fastcall __loadds X_04058(void);
void __near fx_rotary_arm_field(void);
void __near X_04128(void);
void __far __fastcall __loadds fx_rotary_up(void);
void __far __fastcall __loadds fx_rotary_down(void);
void __far __fastcall __loadds fx_rotary_left(void);
void __far __fastcall __loadds fx_rotary_right(void);
void __far __fastcall __loadds X_041CE(void);
void __near fx_autopan_arm_field(void);
void __far __fastcall __loadds X_042C4(void);
void __far __fastcall __loadds X_042E8(void);
void __far __fastcall __loadds X_04306(void);
void __far __fastcall __loadds L_04326(void);
void __far __fastcall __loadds X_04352(void);
void __near fx_pitch_arm_field(void);
void __far __fastcall __loadds fx_pitch_shift_up(void);
void __far __fastcall __loadds fx_pitch_shift_down(void);
void __far T1_br_04490(void);
void __far __fastcall __loadds fx_pitch_shift_left(void);
void __far __fastcall __loadds fx_pitch_shift_right(void);
void __far __pascal ui_screen_enter_chan(long);
void __far __pascal midi_dispatch_table(long);
void __near fx_echo_arm_field(void);
void __far __fastcall __loadds X_04680(void);
void __far __fastcall __loadds X_04696(void);
void __far __fastcall __loadds X_046BA(void);
void __far __fastcall __loadds X_046D2(void);
void __near fx_echo_st_arm_field(void);
void __far __fastcall __loadds X_047DE(void);
void __far __fastcall __loadds X_04802(void);
void __far __fastcall __loadds X_04820(void);
void __far __fastcall __loadds X_0484C(void);
void __far X_04866(void);
void __far __fastcall __loadds X_04876(void);
void __far __fastcall __loadds int2E_read_caller(void);
void __near fx_reverb_arm_field(void);
void __far __fastcall __loadds X_04AE8(void);
void __far __fastcall __loadds X_04B0C(void);
void __far __fastcall __loadds L_04B2A(void);
void __far __fastcall __loadds L_04B42(void);
void __far __pascal audio_dispatch_table(int, int);
void __near midi_status_read(void);
void __far __fastcall __loadds fx_mixer_up(void);
void __far __fastcall __loadds fx_mixer_down(void);
void __far __fastcall __loadds fx_mixer_left(void);
void __far __fastcall __loadds fx_mixer_right(void);
void __far __pascal ui_screen_enter_edit(int, int);
void __near fx_mixer_arm_field(void);
void __far __fastcall __loadds fx_mixer_lr_left(void);
void __far __fastcall __loadds fx_mixer_lr_right(void);
void __far __fastcall __loadds L_04E88(void);
void __near fx_copy_arm_field(void);
void __far __fastcall __loadds copy_fx_up(void);
void __far __fastcall __loadds copy_fx_down(void);
long __near __pascal track_calc_offset(int);
void __near X_04F5A(void);
void __near X_04F76(void);
void __near X_04F9A(void);
void __near X_04FCE(void);
void __near X_04FF2(void);
void __near L_05012(void);
void __far timer_poll_wait_1(void);
void __near L_05074(void);
void __far pad_sw2_clamp(void);
void __near L_050BA_1(void);
void __near X_050E4(void);
void __near X_05116(void);
void __near X_05140(void);
void __near X_05172(void);
void __near L_0518E(void);
void __near assign_view_arm_field(void);
void __far __fastcall __loadds assign_view_key_up(void);
void __far __fastcall __loadds assign_view_key_down(void);
void __far __fastcall __loadds assign_view_key_left(void);
void __far __fastcall __loadds assign_view_key_right(void);
void __far __fastcall __loadds L_052D6(int);
void __far __fastcall __loadds track_read_caller(void);
void __far __fastcall __loadds pgm_assign_enter(void);
void __near L_054DC(void);
void __far __fastcall __loadds L_05534(void);
void __far __fastcall __loadds L_0555A(void);
void __far __fastcall __loadds X_05580(void);
void __far __fastcall __loadds L_055A2(void);
void __far __fastcall __loadds timer_poll_wait_2(void);
void __far __fastcall __loadds L_0560A(int);
void __far X_0576B(void);
void __far __fastcall __loadds X_05776(void);
long __near __pascal track_calc_offset2(int);
void __near timer_dma_sync(void);
void __far __fastcall __loadds X_05950(void);
void __far __fastcall __loadds L_05968(void);
void __far __fastcall __loadds L_05980(void);
void __far __fastcall __loadds L_05998(void);
void __far __fastcall __loadds pad_note_select(int);
void __far __fastcall __loadds timer_poll_wait_3(void);
void __far __fastcall __loadds pgm_params_enter(void);
void __near velo_mod_arm_field(void);
void __far __fastcall __loadds X_05BF6(void);
void __far __fastcall __loadds X_05C0C(void);
void __far __fastcall __loadds timer_status_handler(int);
void __far __fastcall __loadds timer_status_check_1(void);
void __far __fastcall __loadds L_05D2A(void);
void __near timer_poll_wait_4(void);
void __far __fastcall __loadds X_05E0A(void);
void __far __fastcall __loadds X_05E2E(void);
void __far __fastcall __loadds X_05E44(void);
void __far __fastcall __loadds X_05E5C(void);
void __far __fastcall __loadds pad_note_select_2(int);
void __far __fastcall __loadds timer_status_check_2(void);
void __far __fastcall __loadds L_05FC0(void);
void __near velo_pitch_arm_field(void);
void __far __fastcall __loadds T1_L_0607E(void);
void __far __fastcall __loadds L_06096(void);
void __far __fastcall __loadds L_060AE(void);
void __far __fastcall __loadds L_060C6(void);
void __far __fastcall __loadds pad_note_select_3(int);
void __far __fastcall __loadds timer_status_check_3(void);
void __far __fastcall __loadds L_0620E(void);
void __near mute_assign_row_dispatch(void);
void __far __fastcall __loadds X_06286(void);
void __far __fastcall __loadds L_0629C(void);
void __far __fastcall __loadds pad_note_select_4(int);
void __far __fastcall __loadds track_calc_multi_2(void);
void __far __fastcall __loadds L_063DE(void);
void __near program_arm_field(void);
void __far __fastcall __loadds pgm_midi_up(void);
void __far __fastcall __loadds pgm_midi_down(void);
void __far __fastcall __loadds pgm_midi_left(void);
void __far __fastcall __loadds t1_copy_pgm_cancel(void);
void __far __fastcall __loadds purge_midi(void);
void __near L_064F4(void);
void __far __fastcall __loadds X_06540(void);
void __far __fastcall __loadds program_down(void);
void __far __fastcall __loadds L_06570(void);
void __near copy_program_arm_field(void);
void __far __fastcall __loadds X_065CE(void);
void __far __fastcall __loadds L_065E6(void);
void __far __fastcall __loadds program_new(void);
void __near X_06636(void);
void __far __fastcall __loadds t1_program_copy(void);
void __near fn_06680(void);
void __far __fastcall __loadds X_066D6(void);
void __far __fastcall __loadds X_066EC(void);
void __far __fastcall __loadds T1_L_06702(void);
int __near io_near_stub(void);
int __near midi_port_read2(void);
void __near fn_06786(void);
void __far far_067A6(void);
int __near fn_067C2(void);
int __near __pascal io_ctrl_setup(int);
int __near fn_0683A(void);
int __near fn_0686A(void);
void __near io_write_caller(void);
void __near __pascal ctrl_port_18_write(int);
void __far __fastcall __loadds X_06A62(void);
void __near smem_audio_init(void);
void __near smem_write_sample(void);
void __near dma_06CFC(void);
void __near dac_out_program(void);
void __near dma_06E9A(void);
void __near fn_06ECE(void);
void __near fn_06EF2(void);
int __near dma_06F0C(void);
void __near fn_06FB2(void);
void __near dma_06FEC(void);
void __near fn_07030(void);
void __near fn_0704C(void);
int __near dma_pos_reached(void);
void __near fn_070B6(void);
void __near fn_070CC(void);
void __near lcd_update_handler_70E2(void);
void __near lcd_update_handler(void);
void __near lcd_compute_coords(void);
void __near __pascal lcd_clear_display(int, int);
void __far L_07300(void);
void __far tgt_07326(void);
void __far __fastcall __loadds X_07332(void);
void __far __fastcall __loadds L_0733E(void);
#if FW_VERSION == 172
void __far L_07386(void);
#endif
void __far L_07398(void);
void __far L_073A8(void);
void __near rec_arm_field(void);
void __near X_07408(void);
void __near X_0746C(void);
void __far __fastcall __loadds X_07488(void);
void __far __fastcall __loadds X_074A0(void);
void __far __fastcall __loadds X_074B8(void);
void __far __fastcall __loadds X_074CE(void);
void __far __fastcall __loadds lcd_port_handler(int);
void __far __fastcall __loadds L_07524(void);
void __far __fastcall __loadds L_0754E(void);
void __near fn_0761C(void);
void __far __fastcall __loadds X_0765E(void);
void __far __fastcall __loadds ctrl_stub_init(int);
void __far __fastcall __loadds X_07692(void);
void __near X_0769E(void);
void __far __fastcall __loadds X_076BE(void);
void __far __fastcall __loadds X_076D0(void);
void __near fn_076E2(void);
void __far lcd_block_copy_7700(void);
void __near lcd_block_copy(void);
void __far __fastcall __loadds X_0776E(void);
void __far __fastcall __loadds math_calc_handler(void);
void __near trim_start_fine_arm_field(void);
void __near X_07876(void);
void __far __fastcall __loadds X_078A8(void);
void __far __fastcall __loadds X_078D2(void);
void __far __fastcall __loadds X_078F8(void);
void __far __fastcall __loadds X_0790E(void);
void __far __fastcall __loadds trim_screen_enter(void);
void __near start_fine_arm_field(void);
void __far __fastcall __loadds X_0799E(void);
void __far __fastcall __loadds X_079B4(void);
void __far __fastcall __loadds L_079CA(void);
void __near end_fine_arm_field(void);
void __far __fastcall __loadds X_07A2C(void);
void __far __fastcall __loadds X_07A42(void);
void __far __fastcall __loadds L_07A58(void);
void __near string_byte_scan(void);
void __near X_07B2E(void);
void __far __fastcall __loadds X_07B36(void);
void __far __fastcall __loadds X_07B60(void);
void __far __fastcall __loadds X_07B86(void);
void __far __fastcall __loadds X_07B9C(void);
void __far __fastcall __loadds fit_to_length_cancel(void);
void __near L_07BDE(void);
void __far __fastcall __loadds L_07C32(void);
void __far __fastcall __loadds X_07C48(void);
void __far __fastcall __loadds L_07C5E(void);
void __near zone_start_fine_arm_field(void);
void __near T1_br_07CB8(void);
void __far __fastcall __loadds zone_start_fine_up(void);
void __far __fastcall __loadds zone_start_fine_down(void);
void __far __fastcall __loadds zone_start_fine_right(void);
void __far __fastcall __loadds zone_start_fine_left(void);
void __far __fastcall __loadds zone_screen_enter(void);
void __near zone_end_fine_arm_field(void);
void __far __fastcall __loadds X_07DC8(void);
void __far __fastcall __loadds X_07DDE(void);
void __far __fastcall __loadds L_07DF4(void);
void __near zone_edit_arm_field(void);
void __far __fastcall __loadds X_07E50(void);
void __far __fastcall __loadds X_07E66(void);
void __far __fastcall __loadds L_07E7C(void);
int __near __pascal zone_action_new_sample(char __far *, long, long, char __far *);
int __near __pascal zone_action_insert_start(void __far *, long, void __far *);
void __near __pascal main_handler_1(int, int, int, long, int, int);
int __near __pascal tgt_08438(int, int, int, int, int, int);
int __near __pascal zone_action_delete(void __far *, long, long);
void __near __pascal zone_action_reverse(int, int, int, long, int, long);
void __far __fastcall __loadds zone_edit_do_it(void);
void __far br_088B8(void);
void __near trim_arm_field(void);
void __far __fastcall __loadds X_08A0C(void);
void __far __fastcall __loadds X_08A24(void);
void __far __fastcall __loadds X_08A3C(void);
void __far __fastcall __loadds X_08A52(void);
void __far __fastcall __loadds snd_params_screen_enter(void);
int __far X_08A86(void);
int __near main_handler_2(void);
int __far X_08B84(void);
int __near tgt_08BEA(void);
void __near fn_08C4C(void);
void __near fn_08CAA(void);
void __far __fastcall __loadds file_exists_rename(void);
void __far __fastcall __loadds file_exists_refresh(void);
void __near X_08CE6(void);
void __far __fastcall __loadds X_08D02(void);
void __far __fastcall __loadds L_08D0E(void);
void __far __fastcall __loadds X_08D3C(void);
void __near X_08D48(void);
void __far __fastcall __loadds L_08D60(void);
void __far __fastcall __loadds L_08D7E(void);
long __far __pascal sample_name_lookup(long);
long __near midi_active_sense(void);
char __far * __near __pascal sample_block_copy(int);
void __near __pascal lcd_screen_helper(int, int, int, int);
int __near __pascal lcd_area_setup(int, int, int);
int __near __pascal lcd_ratio_calc_90A2(int, int, int);
int __near __pascal lcd_ratio_calc(int);
long __near __pascal lcd_clear_screen(void __far *, char __far *);
long __near __pascal lcd_clear_area(char __far *, int, int);
void __near __pascal lcd_clear_wrapper(long, int);
void __far lcd_area_wrapper_1(long);
void __far lcd_area_wrapper_2(long);
int __near __pascal main_handler_3(int, long, int, long, int, unsigned long);
int __far status_read_multi(char __far *);
void __near __pascal status_poll_delay(long, int);
void __near __pascal int2F_fn5_caller(long);
#if FW_VERSION == 172
void __near __pascal int2F_fn14_setup(int, int, int);
#endif
long __near __pascal status_poll_handler(int, int);
void __near __pascal pad_velocity_handler(int, int);
void __near __pascal envelope_process_1(int, int, long);
long __near __pascal mode_handler(char __far *, int, int);
char __far * __near __pascal voice_play_request(char __far *, char __far *, long);
long __far __pascal int2F_fn14_caller(int, int, int, int);
void __far lcd_fill_buffer(void);
int __far __pascal midi_realtime_start(char __far *);
int __far __pascal midi_realtime_continue(char __far *);
int __near __pascal event_handler(char __far *, int, int);
void __far __fastcall __loadds X_09FE0(void);
void __far tgt_09FFA(void);
void __far __fastcall __loadds X_0A02A(void);
int __near __pascal ctrl_port_78_write(int, int);
void __near __pascal seq_common_handler(long);
void __far __pascal seq_init_navigation(long);
void __far __pascal seq_next_track(long);
void __far __pascal seq_prev_track(long);
int __far seq_event_handler(char __far *, long, long, void __far *);
int __near __pascal track_event_handler(long);
void __near __pascal lcd_clear_line(char __far *, void __far *, long);
int __far smem_access_handler_1(long);
void __near __pascal status_poll_delay2(long, int);
void __near __pascal status_smem_read(long);
void __near __pascal status_poll_handler2(void __far *);
int __near __pascal smem_access_setup(void __far *);
char __far * __near __pascal voice_play_range(long, void __far *);
void __near __pascal int4A_sysex_wrapper(char __far *, int);
void __near fn_0AA0C(void);
void __near fn_0AA44(void);
int __near midi_sysex_handler(void);
void __near __pascal seq_io_control(int, int);
void __near __pascal string_scan_sysex(int, char);
long __near __pascal audio_event_handler(long);
void __near __pascal int4A_proc_caller(char);
void __far L_0ACFE(void);
void __near fn_0AD3A(void);
void __far __fastcall __loadds far_0AD74(void);
void __near midi_txrx_arm_field(void);
void __near X_0AE04(void);
void __far __fastcall __loadds X_0AE58(void);
void __far __fastcall __loadds L_0AE8C(void);
void __far __fastcall __loadds tgt_0AEBA(void);
void __far __fastcall __loadds X_0AEF0(void);
void __far __fastcall __loadds X_0AF30(void);
void __far __fastcall __loadds X_0AF4C(void);
void __far __fastcall __loadds lcd_draw_data(int);
void __far __pascal sysex_sub_dispatch(unsigned char __far *, int);
int __near __pascal lcd_clear_buffer(unsigned char __far *);
void __near fn_0B53E(void);
void __far L_0B5DC(void);
#if FW_VERSION == 172
void __far __fastcall __loadds receive_mode_close(void);
#endif
void __far ui_enter_sound_dialog(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, long);
void __near fn_0B642(void);
void __far __fastcall __loadds tgt_0B650(void);
void __far __fastcall __loadds smem_data_read_handler(void);
void __near __pascal ui_sound_dialog_draw(unsigned char);
void __far __fastcall __loadds keep_or_retry_up(void);
void __far __fastcall __loadds keep_or_retry_down(void);
void __far __fastcall __loadds keep_or_retry_key_33(void);

/* TEXT2 */
int __far L_00026(void);
void __far mpc_rate_caller(void);
void __far __fastcall port_c0_write(int);
int __far port_c0_read(void);
int __far L_000D8(void);
void __far far_000DE(void);
int __far L_00106(void);
int __far L_00116(void);
int __far int4B_wrapper(void);
void __far __pascal int43_wrapper(int);
void __far __pascal int44_wrapper(int);
void __far __pascal cmd_dispatch_1E(unsigned char, char, long);
void __far __pascal cmd_ratio_setup(int, int, char);
void __far cmd_far_stub(void);
void __far __pascal draw_unsigned_value(int, int, long, int);
void __far __pascal draw_signed_value(int, int, long, int);
void __far __pascal ratio_calc_divide(int, int, int, int);
void __far __pascal cmd_dispatch_setup(char, char, int);
void __far __pascal cmd_param_setup(char, char, char, char);
void __far __pascal string_copy_scan(char, char, char *);
void __far __pascal cmd_build_params(int, int, int, int, int);
void __far __pascal display_coord_setup(int);
void __far cmd_far_stub2(void);
void __far __pascal string_copy_setup(char, void);
void __far string_copy_movsb(void);
void __far __pascal cmd_exec_0E_wrapper(int);
void __far __pascal cmd_track_setup(int, int, int);
void __far __pascal cmd_dispatch_0E(int, int, int);
void __far __pascal string_fill_stosb(char *);
void __far __pascal cmd_build_dispatch(int, int, int, int);
void __far __pascal ui_row_request(int);
void __far __pascal cmd_caller_setup(char, char, long);
#if FW_VERSION == 172
void __far L_005B4(void);
#endif
void __far __pascal install_handler(int, void (__far *f)(void));
void __far __pascal install_handler_15(void (__far *f)(void));
void __far X_00610(void);
void __far __fastcall delay_ticks(unsigned);
void __far install_text2_vectors(void);
int __far int2F_bcd_wrapper(void);
void __far int2F_bcd_wrapper2(long);
int __far __pascal mem_block_process(char __far *, int);
int __far __pascal bcd_display_calc(long, int);
long __far __pascal far_memop_caller(long, long);
long __far __pascal bcd_time_format(long, long);
void __far L_00848(void);
void __far L_00946(void);
void __far __pascal bcd_convert(char __far *, char __far *);
long __far __pascal bcd_arithmetic_1(int, long, int, int);
void __far err_msg_report(void);
void __far __fastcall __loadds int45_wrapper(void);
void __far __fastcall __loadds t2_int46_wrapper(void);
void __far __fastcall __loadds X_00AF2(void);
void __far __fastcall __loadds L_00B1A(void);
void __far __fastcall __loadds X_00B3E(void);
void __far __fastcall __loadds cmd_dispatch_handler_1(void);
void __far __fastcall __loadds flash_test_go_handler(void);
void __far __fastcall __loadds disk_media_check(void);
void __far __fastcall __loadds L_00DA6(void);
void __far __fastcall __loadds L_00DE8(void);
int __far X_00DF6(void);
void __far string_copy_cmd(void);
long __far X_00E76(void);
long __far smem_alloc_top(void);
void __far smem_compact(void);
void __far __fastcall port_c2_write(int);
void __far __pascal flash_write_words(unsigned long, int __far *, int);
void __far __pascal smem_read_words(int, long, long);
void __far __pascal smem_dma_copy(int, long, long, int);
void __far __pascal smem_copy_buffered(long, long, long);
void __far __pascal input_handler(long, long, long);
void __far __pascal smem_fill(long, int, long);
int __far __pascal samples_to_tenths(long);
void __far __interrupt X_0124E(void);
int __far __pascal mem_io_handler(int __far *, long, int);
void __far flash_board_idle(void);
void __far flash_vpp_on(void);
void __far far_012E2(void);
void __far far_012F0(void);
void __far __pascal flash_read_identifier(unsigned long);
void __far __pascal mem_op_wrapper_2(unsigned long);
void __far __pascal mem_op_wrapper_3(int, int, int);
void __far __pascal io_delay_wait(unsigned long);
void __far __pascal mem_op_wrapper_4(unsigned long, int __far *, int);
void __far __pascal mem_op_wrapper_5(unsigned long, int);
int __far __pascal mem_op_handler(long, char __near *);
int __far __pascal io_delay_wait2(unsigned long);
void __far __pascal system_call_handler(int, int, int, int, int);
void __far __pascal string_memop_setup(long);
int __far __pascal memcpy_far_seg(unsigned, unsigned, int);
int __far __fastcall dma_01600(int);
void __far dma_status_rearm(void);
int __far L_01610(void);
void __far L_0162A(void);
long __far __pascal dma_field_write(int, char __far *, int);
int __far __fastcall X_01806(int);
void __far mpc_poll_status(void);
long __far __fastcall X_0184A(int);
int __far L_01872(void);
void __far __pascal asic_reg1_write(int, int);
int __far L_018D0(void);
void __far dma_018ee(void);
void __far __pascal lcd_write_data(unsigned, unsigned, unsigned);
void __far L_01A0C(void);
void __far timer_system(void);
void __far __pascal pending_ops_set(char);
void __far __interrupt L_01A70(void);
void __far X_01AD4(void);
void __far __pascal smem_dma_channel_01(unsigned char);
void __far __pascal lcd_clear_region_impl(unsigned char, char);
void __far far_01B6C(void);
void __far __pascal smem_dma_channel_23(unsigned char);
void __far __pascal lcd_clear_rect(unsigned char, char);
void __far lcd_write_block_D3B2(void);
void __far dsp_chan_reg_clear(void);
void __far L_01D18(void);
void __far __pascal dsp_chan_update(char, char);
void __far __pascal mpc_poll_data(int);
void __far __pascal mpc_poll_data2(int);
int __far far_01D98(void);
void __far sound_event_dispatch(unsigned char, unsigned char, char);
void __far __pascal smem_addr_data_ctrl(int);
void __far __pascal smem_addr_data_ctrl2(char, char);
void __far __pascal tgt_01ECE(int, char);
void __far __pascal far_01F00(int);
void __far __pascal smem_addr_data_status(char __far *);
void __far __pascal pad_note_release(int);
void __far __pascal note_off_voices(int);
void __far sample_dma_setup_large(void);
int __far __pascal string_scan_status(long, long);
void __far __pascal pad_event_dispatch(int, int);
int __far X_020AE(void);
void __far __pascal voice_buf_helper_1(int);
void __far __pascal voice_buf_helper_2(int);
void __far __interrupt X_02124(void);
int __far __pascal voice_timer_expire(int);
void __far __pascal voice_timer_tick(int);
void __far sample_error_handler(void);
int __far __pascal voice_alloc(int);
void __far __pascal voice_regs_program(void __far *);
void __far __pascal voice_release_by_note(int);
void __far __pascal voice_start(void __far *, int, int, int);
void __far voice_release_all(void);
void __far __pascal voice_release_full(unsigned);
void __far __pascal voice_release(int);
void __far __pascal lcd_set_cursor(void __far *);
void __far __pascal voice_release_all_if(long);
void __far __pascal voice_start_sample(void __far *, long, long);
void __far __pascal midi_note_io(long);
void __far X_02C66(void);
int __far midi_note_process(unsigned char, unsigned char, unsigned char);
void __far X_02D4A(void);
void __far __fastcall __loadds X_02D54(int, int);
void __far __fastcall __loadds X_02D76(int, int);
void __far __fastcall __loadds X_02DA0(void);
void __far field_edit_disable(void);
void __far far_02DC8(void);
void __far far_02DD2(void);
void __far win_keys_merge_disable(void);
void __far field_redraw(void);
void __far field_draw_default(void);
long __far __pascal field_value_store(int, int);
void __far __fastcall __loadds field_value_scale(void);
void __far __fastcall __loadds field_value_scale_2(void);
void __far __fastcall __loadds seq_read_data(int);
void __far field_value_commit(void);
void __far __pascal status_read_6A(long, int, int, char, char, char, long, long);
void __far __pascal status_read_6A_2(long, int, int, char, char, char, long, long);
void __far __pascal status_read_6A_3(long, unsigned char, unsigned char, char, char, char, long, long);
void __far __pascal field_register_s8(long, char, char, char, char, char, long, long);
void __far __fastcall __loadds name_edit_commit(void);
void __far X_03432(void);
void __far __fastcall __loadds voice_port_read(void);
void __far __fastcall __loadds voice_port_read2(void);
void __far __fastcall __loadds midi_channel_handler(int);
void __far __fastcall __loadds midi_msg_io(int);
void __far __fastcall __loadds X_035EC(void);
void __far __fastcall __loadds L_03614(void);
void __far __fastcall __loadds X_0362C(int, int);
void __far __fastcall __loadds T2_X_03656(int, int);
void __far __fastcall __loadds X_0367A(void);
void __far __fastcall __loadds far_0369C(void);
void __far __fastcall __loadds X_036C0(void);
void __far __fastcall __loadds X_036F0(void);
void __far __fastcall __loadds L_03746(void);
void __far __fastcall __loadds T2_L_037AA(void);
void __far __pascal timer_dma_ch2(long, char, char, char, char, char, long, long);
void __far L_03808(void);
void __far X_03840(void);
void __far __pascal voice_trigger_full(long, char, char, char, char, long);
void __far __pascal timer_value_read_1(char __far *, int, int, int);
void __far __pascal timer_value_read_2(char, long);
void __far __pascal cmd_dispatch_wrapper(int, int, int);
void __far __pascal timer_value_read_3(char, int, int);
void __far __pascal timer_value_read_4(int, int, int, int);
void __far __pascal display_draw_coord(long, int, int);
void __far __pascal timer_value_read_5(int, long);
void __far name_edit_change_default(void);
void __far L_03ADC(void);
int __far __fastcall X_03B24(int);
void __far timer_loop_io(void);
void __far __fastcall __loadds show_dev_credits_scroll(int);
void __far __fastcall __loadds L_03C30(void);
void __far __fastcall __loadds L_03C56(void);
#if FW_VERSION == 172
int __far L_03C6C(void);
#endif
void __far __pascal voice_block_copy(char __far *);
void __far __fastcall __loadds L_03CF8(void);
void __far __fastcall __loadds X_03D0E(void);
void __far __pascal mpc_port_C1_5E(int, int);
void __far __fastcall __loadds L_03D56(void);
void __far __fastcall __loadds tgt_03D80(void);
void __far __fastcall __loadds far_03DAA(void);
void __far __fastcall __loadds L_03DD4(void);
int __far __fastcall __loadds L_03DFE(void);
long __far __fastcall __loadds cmd_exec_quad(void);
void __far __fastcall __loadds L_03F68(void);
#if FW_VERSION == 172
void __far __fastcall __loadds L_03F84(void);
#endif
#if FW_VERSION == 172
void __far __fastcall __loadds L_03F92(void);
#endif
long __far __pascal note_clamp_multi(int, int, int);
void __far __pascal voice_param_proc(int, int, int);
char __far * __far __pascal note_clamp_flag(int);
char __far * __far __pascal note_range_clamp(int);
void __far __pascal read_io_chain(char, int);
void __far __fastcall __loadds X_04138(void);
long __far channel_validate(int);
long __far channel_get_ptr(int);
void __far __fastcall __loadds far_04206(void);
void __far __fastcall __loadds X_0425A(void);
void __far L_0426A(void);
void __far __fastcall __loadds L_04270(void);
void __far __pascal track_select_setup(int, int, char __far *);
void __far __pascal cmd_sequence_handler(int, int);
void __far L_043E2(void);
void __far L_043EE(void);
void __far L_04422(void);
void __far X_04428(void);
void __far __pascal voice_process_setup(int);
void __far X_0449E(void);
void __far L_0454E(void);
void __far X_0455A(void);
void __far __fastcall __loadds L_04588(void);
void __far __fastcall __loadds L_045AA(void);
void __far __fastcall __loadds L_045BA(void);
void __far __fastcall __loadds track_process_full(void);
void __far __fastcall __loadds track_process_ext(void);
void __far __fastcall __loadds X_04888(void);
void __far __pascal cmd_exec_pair(int, int, int, int);
void __far num_entry_draw(void);
void __far X_049DA(void);
void __far __pascal cmd_exec_1E(int, int, int);
void __far __pascal cmd_dispatch_caller2(int, int, char);
void __far __pascal cmd_dispatch_handler_2(int, int, char);
#if FW_VERSION == 172
void __far L_04B2E_1(void);
#endif
void __far fx_redraw(void);
void __far far_04B42(void);
void __far __pascal voice_process_triple(int);
void __far __pascal voice_dispatch_table(int);
void __far fx_type_load(void);
void __far __fastcall __loadds tgt_04C68(int);
void __far __fastcall __loadds far_04C8A(void);
void __far __fastcall __loadds L_04CB0(void);
void __far __fastcall __loadds X_04CC2(void);
void __far L_04CEE(void);
void __far __fastcall __loadds L_04CFA(void);
void __far __fastcall __loadds L_04D0A(void);
void __far L_04D1A(void);
void __far __fastcall __loadds filter4_f2(void);
void __far __fastcall __loadds filter4_f3(void);
void __far far_04D46(void);
void __far X_04D6C(void);
void __far __fastcall __loadds L_04D7E(void);
void __far fx_type_load_select(void);
void __far __fastcall __loadds L_04DC4(void);
void __far __fastcall __loadds L_04DD4(void);
void __far L_04DE4(void);
void __far X_04E24(void);
void __far __fastcall __loadds fx_chorus_paint(void);
void __far __fastcall __loadds fx_rotary_paint(void);
void __far __fastcall __loadds L_04F44(void);
int __far __pascal lcd_init_setup(int);
int __far __pascal voice_ratio_calc(int);
void __far __pascal lcd_init_display(int, int, int);
void __far L_050AA(void);
void __far __pascal cmd_exec_multi(char __far *, int, int);
void __far __fastcall __loadds status_read_6A_4(void);
void __far __fastcall __loadds L_051DA(void);
void __far L_051EE(void);
void __far __fastcall __loadds L_051FA(void);
void __far __fastcall __loadds L_0520A(void);
void __far L_0521A(void);
long __far L_050DC(void);
void __far L_0522C(void);
void __far __fastcall __loadds cmd_exec_2(void);
void __far __fastcall __loadds L_052E8(void);
void __far L_0538E(void);
void __far __fastcall __loadds L_0539A(void);
void __far __fastcall __loadds L_053AA(void);
void __far L_053BA(void);
void __far __fastcall __loadds cmd_exec_7(void);
void __far L_054E4(void);
void __far __fastcall __loadds fx_mixer_lr_paint(void);
void __far __fastcall __loadds cmd_block_copy(void);
void __far __fastcall __loadds copy_fx_close(void);
void __far __fastcall __loadds copy_fx_paint(void);
int __far far_05700(void);
int __far __pascal int38_call_9e(int);
void __far __pascal int38_call_02(int);
int __far __pascal int38_call_pair(int, int);
void __far L_05760(void);
void __far smem_io_helper(void);
void __far __pascal cmd_exec_1E_ext(int);
void __far __pascal cmd_dispatch_handler_3(int, int);
void __far L_05844(void);
void __far __pascal program_select(int);
int __far __pascal program_select_wrapper(int);
void __far __pascal smem_dma_init(int);
void __far X_05972(void);
int __far __pascal smem_access_handler_2(long);
int __far far_059BC(void);
char __far * __far __pascal _memcpy_2(char __far *, int);
void __far __pascal far_memop_handler_1(int);
void __far __pascal _memset_2(int, int);
void __far __pascal far_memop_str_1(char __far *);
void __far __pascal _memcpy_3(struct FXS __far *);
void __far __pascal far_memop_str_2(int, long);
int __far __pascal timer_io_setup(int);
void __far __pascal rep_memcpy_handler(int, int, int, int);
void __far __pascal smem_proc_wrapper(long);
void __far smem_transfer_io(void);
void __far __pascal seq_select_setup_1(long);
void __far __pascal seq_select_setup_2(long);
void __far L_05D1E(void);
void __far loop_seq_handler(void);
void __far smem_loop_proc(void);
void __far __fastcall __loadds L_05C0E(void);
void __far __fastcall __loadds smem_rep_str(void);
void __far __fastcall __loadds L_05DD6(void);
void __far __fastcall __loadds L_05E02(void);
void __far __fastcall __loadds L_05E34(void);
void __far __pascal seq_transfer_io(int, int, int, int, int);
void __far L_05EEE(void);
void __far __fastcall __loadds L_05EFA(void);
void __far __fastcall __loadds pgm_midi_key_33(void);
void __far __fastcall __loadds pgm_midi_refresh(void);
void __far __fastcall __loadds pgm_midi_paint(void);
#if FW_VERSION == 172
long __far __pascal smem_addr_dma_read(int, int);
#endif
#if FW_VERSION == 172
long __far __pascal smem_addr_dma_read2(long);
#endif
#if FW_VERSION == 172
long __far __pascal smem_addr_dma_read3(int, int);
#endif
#if FW_VERSION == 172
void __far sample_gc(void);
#endif
int __far sample_unused_count(void);
void __far __fastcall __loadds L_0619E(void);
#if FW_VERSION == 172
void __far __fastcall __loadds purge_do_it(void);
#endif
#if FW_VERSION == 172
void __far __fastcall __loadds purge_paint(void);
#endif
#if FW_VERSION == 172
void __far __fastcall __loadds L_06206(void);
#endif
void __far __fastcall __loadds pgm_assign_key(void);
void __far __fastcall __loadds seq_port_io(void);
void __far __fastcall __loadds seq_port_io2(void);
void __far __fastcall __loadds note_release_latched(void);
void __far __pascal sequence_get_info(int, int, int);
void __far __pascal seq_write_data(long, int, char, char, long, long);
void __far __fastcall __loadds program_close(void);
void __far __fastcall __loadds copy_pgm_refresh(void);
void __far __fastcall __loadds program_paint(void);
void __far __fastcall __loadds t2_copy_pgm_cancel(void);
void __far X_064CC(void);
void __far __fastcall __loadds delete_pgm_do_it(void);
void __far __fastcall __loadds delete_pgm_paint(void);
void __far __fastcall __loadds program_delete(void);
void __far X_0655C(void);
void __far __fastcall __loadds L_06580(void);
void __far __fastcall __loadds delete_all_pgms_do_it(void);
void __far __fastcall __loadds delete_all_pgms_paint(void);
void __far __fastcall __loadds delete_pgm_allpgm(void);
void __far __fastcall __loadds seq_select_caller(void);
void __far __fastcall __loadds L_0666A(void);
void __far __fastcall __loadds copy_pgm_do_it(void);
void __far __fastcall __loadds copy_pgm_paint(void);
void __far __fastcall __loadds X_067E8(void);
void __far __fastcall __loadds far_06834(void);
void __far __fastcall __loadds L_0684A(void);
void __far __fastcall __loadds mixer_stereo_page(void);
void __far __pascal note_pitch_calc_1(int);
void __far __pascal note_pitch_calc_2(int);
void __far __pascal note_pitch_calc_3(int);
void __far __pascal note_str_handler(int);
void __far __pascal note_pitch_calc_cmd(int, int);
void __far __pascal dispatch_handler_2(int);
void __far __fastcall __loadds mixer_indiv_page(void);
void __far __pascal note_range_calc_1(int);
void __far __pascal note_range_calc_2(int);
void __far __pascal bcd_arithmetic_2(int);
void __far __pascal bcd_arithmetic_3(int);
void __far __pascal note_cmd_helper(int, int);
void __far __pascal dispatch_handler_1(int);
void __far __fastcall __loadds mixer_fxsend_page(void);
void __far __pascal note_range_calc_3(int);
void __far __pascal note_range_calc_4(int);
void __far __pascal timer_dma_setup(int);
void __far __pascal timer_dma_setup2(int);
int __far __pascal note_range_calc_cmd(int, int);
void __far __pascal timer_dma_setup3(int);
void __far __pascal sample_dispatch_table(int);
void __far __fastcall __loadds timer_read_caller(void);
void __far L_070FA(void);
void __far mix_pan_store(void);
void __far L_07136(void);
void __far L_07154(void);
void __far timer_poll_wait_5(void);
void __far L_071AE(void);
void __far L_071CC(void);
void __far timer_str_handler(void);
void __far X_0724A(void);
void __far __fastcall __loadds channel_settings_up(void);
void __far __fastcall __loadds channel_settings_down(void);
void __far __fastcall __loadds channel_settings_left(void);
void __far __fastcall __loadds channel_settings_right(void);
void __far __fastcall __loadds pad_note_select_5(unsigned);
void __far __fastcall __loadds channel_settings_close(void);
void __far far_074EE(void);
char __far * __far __pascal sample_pool_add(void);
void __far __pascal sample_validate_ptr(int, int);
void __far sample_data_load_1(void);
void __far sample_delete_flagged(void);
void __far sample_addr_from_disk(void);
void __far __pascal sample_desc_init(void __far *);
long __far far_078E4(void);
int __far far_07900(void);
int __far sample_caller_setup(void);
long __far __pascal sample_ptr_access(char __far *);
struct SND __far * __far __pascal sample_data_load_2(char __far *);
int __far __pascal sample_ptr_helper(long);
int __far __pascal sample_check_active(struct SND __far *);
void __far __pascal sample_data_load_3(void (__far *)(void));
int __far __pascal fdc_port_90_access(char __far *, char __far *);
void __far X_07C12(void);
int __far __pascal timer_fdc_sync(int, long);
void __far __pascal tgt_07C8E(int, int);
char __far * __far __pascal sample_ptr_accessor(char __far *, char __far *);
void __far __fastcall __loadds X_07D92(void);
void __far __fastcall __loadds tgt_07DB2(void);
void __far __pascal sample_calc_offset(int, int, int);
void __far edit_range_select(void);
void __far X_07ED0(void);
void __far __fastcall __loadds X_07F14(void);
void __far __pascal mode_dispatch_index(int, int);
void __far __pascal voice_trigger_caller(char, char, char __far *);
void __far __pascal ui_field_edit(long, char, char, long, long, long, char __far *);
void __far __fastcall __loadds snd_window_refresh_key(void);
void __far __fastcall __loadds snd_window_pad_key(int);
void __far far_08010(void);
void __far __pascal cmd_exec_caller(long, long);
void __far __pascal voice_buffer_init(char __far *);
void __far cmd_ratio_calc(void);
void __far __pascal words_minmax(long, int, int __far *, int __far *);
long __far string_op_setup(void);
void __far string_func_handler(void);
void __far sample_name_search(void);
void __far __pascal cmd_write_caller(long);
void __far __fastcall __loadds X_085E6(void);
int __far __pascal sample_load_wrapper(long);
void __far __pascal sample_calc_length(int, int, char __far *);
void __far __fastcall __loadds X_08736(void);
void __far __fastcall __loadds tgt_087D4(void);
void __far __fastcall __loadds snd_edit_page_return(void);
void __far __fastcall __loadds sample_voice_init(void);
void __far __fastcall __loadds delete_sound_paint(void);
void __far __fastcall __loadds L_0855C(void);
void __far __fastcall __loadds L_0893A(void);
void __far __fastcall __loadds delete_all_sounds_do_it(void);
void __far __fastcall __loadds delete_all_sounds_paint(void);
void __far __fastcall __loadds delete_sound_all(void);
void __far __fastcall __loadds voice_init_caller(void);
void __far __fastcall __loadds L_0865E(void);
void __far __fastcall __loadds L_08A3C(void);
void __far __fastcall __loadds L_0868A(void);
void __far __fastcall __loadds L_08A68(void);
void __far sample_data_far_1(void);
void __far L_08B5E(void);
void __far sample_data_far_2(void);
void __far sample_str_scan_1(void);
void __far __pascal sample_active_check_1(int, int, void (__far *)(void));
void __far sample_data_far_3(void);
void __far L_08E48(void);
void __far sample_data_far_4(void);
void __far sample_str_scan_2(void);
void __far __pascal sample_active_check_2(int, int, void (__far *)(void));
void __far L_09092(void);
void __far X_090B2(void);
void __far L_090D4(void);
void __far L_090E6(void);
void __far X_090F4(void);
void __far __fastcall __loadds L_09116(void);
void __far __fastcall __loadds X_09124(void);
void __far __fastcall __loadds wave_zoom_double(void);
void __far __fastcall __loadds wave_zoom_halve(void);
void __far __fastcall __loadds L_09210(void);
void __far __fastcall __loadds L_09292(void);
void __far __fastcall __loadds X_092A8(void);
void __far __fastcall __loadds L_092C2(void);
void __far __fastcall __loadds L_09344(void);
void __far __fastcall __loadds X_0935A(void);
void __far sample_event_handler(void);
void __far __fastcall __loadds discard_do_it(void);
void __far __fastcall __loadds discard_paint(void);
void __far __fastcall __loadds L_09544(void);
void __far sample_str_scan_4(void);
void __far sample_str_scan_5(void);
void __far __pascal ui_edit_position(int, int, long);
void __far sample_data_far_5(void);
void __far sample_str_scan_6(void);
void __far __pascal sample_active_check_3(int, int, long);
void __far L_09900(void);
void __far __fastcall __loadds L_0990E(void);
void __far __fastcall __loadds X_0991C(void);
void __far __fastcall __loadds display_draw_pair(void);
void __far __fastcall __loadds L_09A72(void);
void __far __fastcall __loadds X_09A88(void);
void __far __fastcall __loadds fit_to_length_paint(void);
void __far __fastcall __loadds track_data_far(void);
void __far __fastcall __loadds X_09B20(void);
void __far __pascal track_block_copy(char __far *, long, int);
int __far zone_range_clamp(void);
void __far tgt_09C42(void);
void __far __pascal ui_edit_zone_start(int, int, void (__far *)(void));
int __far L_09CE8(void);
int __far X_09D06(void);
void __far __pascal ui_edit_zone_end(int, int, void (__far *)(void));
void __far __fastcall __loadds zone_start_fine_key_33(void);
void __far __fastcall __loadds zone_start_fine_paint(void);
void __far __fastcall __loadds L_09E4E(void);
void __far __fastcall __loadds L_09EBA(void);
void __far __fastcall __loadds X_09ED0(void);
void __far __fastcall __loadds X_09EEA(void);
void __far __fastcall __loadds X_09F56(void);
void __far __fastcall __loadds X_09F6C(void);
void __far __fastcall __loadds zone_edit_paint(void);
void __far br_0A00C(void);
void __far br_0A026(void);
void __far __fastcall __loadds zone_edit_up(void);
void __far __fastcall __loadds L_0A07A(void);
void __far X_0A0A2(void);
void __far __fastcall __loadds zone_edit_cancel(void);
void __far __fastcall __loadds X_0A0CA(void);
int __far midi_realtime_stop(long, int, int, char, int);
int __far tgt_0A308(void);
int __far range_seq_caller(void);
int __far __pascal range_smem_setup(int, int);
void __far __pascal range_proc_setup(int);
int __far __pascal range_process(char __far *, int, int, int, int);
long __far __pascal range_io_handler(int, int, int, unsigned);
int __far far_0A682(void);
int __far far_0A6FA(void);
long __far __pascal sample_process_setup(long, long, int);
void __far sample_process_1(void);
int __far midi_realtime_stop2(int, int, int, int);
int __far tgt_0AA60(void);
long __far smem_init_handler(void);
void __far sample_proc_wrapper(void);
void __far __pascal lcd_line_copy(long, long);
void __far __pascal _memcpy_1650C(long, int, int);
void __far __pascal lcd_region_helper(int, int, long);
void __far __pascal lcd_buffer_copy(char __far *, char __far *);
void __far __pascal lcd_region_copy(char __far *, char __far *);
void __far __pascal lcd_line_clear(char __far *, char __far *);
void __far __pascal lcd_cmd_wrapper(char __far *);
void __far __fastcall __loadds X_0B090(void);
void __far __fastcall __loadds L_0B0BE(void);
int __far __pascal sample_proc_helper(long);
void __far __pascal sample_data_copy(int, long, long);
void __far __pascal _memcpy_5(struct SND __far *, struct SND __far *);
int __far __pascal sample_access_caller(char __far *, int);
void __far __fastcall __loadds file_exists_paint(void);
void __far __fastcall __loadds X_0B27A(void);
void __far __fastcall __loadds X_0B290(void);
void __far __fastcall __loadds X_0B2A6(void);
void __far __fastcall __loadds X_0B2C0(void);
void __far __pascal ui_enter_pad_assign(long);
int __far sample_ptr_caller(char __far *);
int __far __pascal midi_calc_timing(long, int);
void __far __pascal midi_out_io(int, unsigned);
int __far int4D_sample_wrapper(void);
int __far __pascal midi_out_io2(int);
long __far __pascal midi_out_io3(unsigned);
long __far __pascal midi_io_chain(int, int);
int __far midi_string_handler(char __far *, int, int, char, int, int, int, void (__far *cb)(void));
void __far sample_process_2(void);
void __far midi_prog_change(void);
void __far __pascal sample_io_handler(long, long, int);
int __far midi_string_setup(void);
char __far * __far __pascal midi_stop_helper(int, char __far *);
int __far tgt_0BC26(void);
void __far far_0BC30(void);
void __far __fastcall __loadds sample_calc_position(void);
void __far __fastcall __loadds load_sound_up(void);
void __far __fastcall __loadds load_sound_down(void);
void __far __fastcall __loadds load_sound_refresh(void);
void __far __fastcall __loadds smem_read_handler(void);
int __far __pascal sample_load_entry(char __far *__far *, int);
int __far sample_load_step(void);
void __far far_0C228(void);
void __far X_0C236(void);
void __far __fastcall __loadds change_disk_refresh(void);
void __far __fastcall __loadds change_disk_paint(void);
void __far __fastcall __loadds change_disk_do_it(void);
int __far __pascal sample_create(int);
int __far __pascal smem_block_alloc(int __far *, long);
int __far __pascal sample_data_load_12bit(long, long);
int __far __pascal ctrl_port_caller(long, long);
int __far __pascal ctrl_io_access(long);
int __far __pascal smem_access_handler_3(long);
int __far sample_index_rebuild(void);
int __far smem_ctrl_setup_1(void);
int __far __pascal ctrl_port_48_B8(int);
int __far __pascal pgm_file_write(long);
int __far __pascal ctrl_port_48_B8_3(char __far *);
int __far __pascal smem_ctrl_setup_2(long, int);
int __far __pascal ctrl_port_48_read(long, int);
int __far __pascal envelope_process_2(char __far *);
void __far __pascal _memcpy_6(long, long);
void __far __pascal ctrl_port_48_read2(char __far *);
long __far __pascal far_memop_handler_2(int, int, int, int);
long __far far_0CDBA(void);
void __far L_0CDD8(void);
int __far __pascal sample_access_short(long);
void __far __pascal sample_access_triple(int, int);
long __far __pascal int40_disk_wrapper(char __far *);
long __far __pascal smem_block_skip(long);
long __far __pascal memcpy_far_handler(int, int);
int __far __pascal ctrl_io_setup(long, long);
void __far __fastcall __loadds data_far_write(void);
void __far __fastcall __loadds L_0CDEC(void);
void __far __fastcall __loadds L_0D24E(void);
void __far __fastcall __loadds L_0CDFE(void);
void __far __fastcall __loadds L_0D260(void);
void __far __fastcall __loadds L_0D272(void);
#if FW_VERSION == 172
void __far __fastcall __loadds L_0D282(void);
#endif
#if FW_VERSION == 172
void __far __fastcall __loadds receive_mode_paint(void);
#endif
#if FW_VERSION == 172
void __far __fastcall __loadds receive_mode_refresh(void);
#endif
void __far __fastcall __loadds keep_or_retry_paint(void);
void __far __fastcall __loadds X_0D332(void);
void __far __fastcall __loadds X_0D344(void);
void __far __fastcall __loadds X_0D356(void);
void __far string_far_access(void);
void __far __fastcall __loadds mono_to_stereo_paint(void);
void __far __fastcall __loadds mono_to_stereo_up(void);
void __far __fastcall __loadds mono_to_stereo_down(void);
void __far __fastcall __loadds sample_string_access(void);
void __far string_int_access(void);
void __far __fastcall __loadds stereo_to_mono_paint(void);
void __far __fastcall __loadds stereo_to_mono_up(void);
void __far __fastcall __loadds stereo_to_mono_down(void);
void __far __fastcall __loadds sample_process_large(void);
void __far fn_0D9CE(int);

/* not image functions: the runtime library and names C reaches by label */
long __far X_004C2(void);
void __far * __far _fmemcpy(void __far *, const void __far *, unsigned);
int __far _fstricmp(const char __far *, const char __far *);
char __far * __far _fstrncpy(char __far *, const char __far *, unsigned);
int __far _setjmp(char __far *);
void * __far memcpy(void *, const void *, unsigned);
void * __far memset(void *, int, unsigned);
char * __far strcat(char *, const char *);
int __far strcmp(const char *, const char *);
char * __far strcpy(char *, const char *);
unsigned __far strlen(const char *);
long __far __interrupt sub_18166(void);

#endif
